
package br.com.publicacao.webservice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.16
 * Mon Apr 17 12:25:05 BRT 2017
 * Generated source version: 2.7.16
 */

@XmlRootElement(name = "inserirPublicacao", namespace = "http://webservice.publicacao.com.br/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "inserirPublicacao", namespace = "http://webservice.publicacao.com.br/")

public class InserirPublicacao {

    @XmlElement(name = "arg0")
    private br.com.publicacao.vo.Publicacao arg0;

    public br.com.publicacao.vo.Publicacao getArg0() {
        return this.arg0;
    }

    public void setArg0(br.com.publicacao.vo.Publicacao newArg0)  {
        this.arg0 = newArg0;
    }

}

