
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package br.com.publicacao.webservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2017-04-17T12:33:41.049-03:00
 * Generated source version: 2.7.16
 * 
 */

@javax.jws.WebService(
                      serviceName = "PublicacoesWebServiceService",
                      portName = "PublicacoesWebServicePort",
                      targetNamespace = "http://webservice.publicacao.com.br/",
                      wsdlLocation = "http://localhost:8080/PublicacaoProducer/services/PublicacoesWebServicePort?wsdl",
                      endpointInterface = "br.com.publicacao.webservice.PublicacoesWebService")
                      
public class PublicacoesWebServiceImpl implements PublicacoesWebService {

    private static final Logger LOG = Logger.getLogger(PublicacoesWebServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see br.com.publicacao.webservice.PublicacoesWebService#excluirAutor(br.com.publicacao.webservice.Autor  arg0 )*
     */
    public int excluirAutor(br.com.publicacao.webservice.Autor arg0) { 
        LOG.info("Executing operation excluirAutor");
        System.out.println(arg0);
        try {
            int _return = 153020885;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see br.com.publicacao.webservice.PublicacoesWebService#excluirPublicacao(int  arg0 )*
     */
    public int excluirPublicacao(int arg0) { 
        LOG.info("Executing operation excluirPublicacao");
        System.out.println(arg0);
        try {
            int _return = 1452230269;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see br.com.publicacao.webservice.PublicacoesWebService#inserirAutor(br.com.publicacao.webservice.Autor  arg0 )*
     */
    public int inserirAutor(br.com.publicacao.webservice.Autor arg0) { 
        LOG.info("Executing operation inserirAutor");
        System.out.println(arg0);
        try {
            int _return = -519391453;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see br.com.publicacao.webservice.PublicacoesWebService#buscarPublicacoes(java.lang.String  arg0 )*
     */
    public br.com.publicacao.webservice.Publicacao buscarPublicacoes(java.lang.String arg0) { 
        LOG.info("Executing operation buscarPublicacoes");
        System.out.println(arg0);
        try {
            br.com.publicacao.webservice.Publicacao _return = new br.com.publicacao.webservice.Publicacao();
            _return.setDataPublicacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-17T12:33:41.068-03:00"));
            _return.setId(Integer.valueOf(6822804));
            _return.setPagFinal(Integer.valueOf(403520153));
            _return.setPagInicial(Integer.valueOf(-1396671290));
            _return.setTitulo("Titulo1032835024");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see br.com.publicacao.webservice.PublicacoesWebService#buscarAutor(java.lang.String  arg0 )*
     */
    public br.com.publicacao.webservice.Autor buscarAutor(java.lang.String arg0) { 
        LOG.info("Executing operation buscarAutor");
        System.out.println(arg0);
        try {
            br.com.publicacao.webservice.Autor _return = new br.com.publicacao.webservice.Autor();
            _return.setCpf("Cpf-125101494");
            br.com.publicacao.webservice.Endereco _returnEndereco = new br.com.publicacao.webservice.Endereco();
            _returnEndereco.setBairro("Bairro-1297827526");
            _returnEndereco.setCep(Integer.valueOf(-1579530574));
            _returnEndereco.setCidade("Cidade1101583895");
            _returnEndereco.setEndereco("Endereco802886011");
            _returnEndereco.setId(Integer.valueOf(-344006234));
            _returnEndereco.setIdAutor(Integer.valueOf(-927424882));
            _returnEndereco.setUf("Uf184573537");
            _return.setEndereco(_returnEndereco);
            _return.setId(Integer.valueOf(-545113624));
            _return.setNome("Nome-217431742");
            _return.setNomeCitacao("NomeCitacao1458167496");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see br.com.publicacao.webservice.PublicacoesWebService#alterarAutor(br.com.publicacao.webservice.Autor  arg0 )*
     */
    public int alterarAutor(br.com.publicacao.webservice.Autor arg0) { 
        LOG.info("Executing operation alterarAutor");
        System.out.println(arg0);
        try {
            int _return = 348906583;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see br.com.publicacao.webservice.PublicacoesWebService#isCPF(java.lang.String  arg0 )*
     */
    public boolean isCPF(java.lang.String arg0) { 
        LOG.info("Executing operation isCPF");
        System.out.println(arg0);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see br.com.publicacao.webservice.PublicacoesWebService#inserirPublicacao(br.com.publicacao.webservice.Publicacao  arg0 )*
     */
    public int inserirPublicacao(br.com.publicacao.webservice.Publicacao arg0) { 
        LOG.info("Executing operation inserirPublicacao");
        System.out.println(arg0);
        try {
            int _return = 602836289;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see br.com.publicacao.webservice.PublicacoesWebService#alterarPublicacao(br.com.publicacao.webservice.Publicacao  arg0 )*
     */
    public int alterarPublicacao(br.com.publicacao.webservice.Publicacao arg0) { 
        LOG.info("Executing operation alterarPublicacao");
        System.out.println(arg0);
        try {
            int _return = -993281100;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
