
package br.com.publicacao.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2017-04-17T12:33:40.966-03:00
 * Generated source version: 2.7.16
 * 
 */
public final class PublicacoesWebService_PublicacoesWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.publicacao.com.br/", "PublicacoesWebServiceService");

    private PublicacoesWebService_PublicacoesWebServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PublicacoesWebServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PublicacoesWebServiceService ss = new PublicacoesWebServiceService(wsdlURL, SERVICE_NAME);
        PublicacoesWebService port = ss.getPublicacoesWebServicePort();  
        
        {
        System.out.println("Invoking excluirAutor...");
        br.com.publicacao.webservice.Autor _excluirAutor_arg0 = new br.com.publicacao.webservice.Autor();
        _excluirAutor_arg0.setCpf("Cpf710309018");
        br.com.publicacao.webservice.Endereco _excluirAutor_arg0Endereco = new br.com.publicacao.webservice.Endereco();
        _excluirAutor_arg0Endereco.setBairro("Bairro1543893925");
        _excluirAutor_arg0Endereco.setCep(Integer.valueOf(1869123470));
        _excluirAutor_arg0Endereco.setCidade("Cidade-1819121230");
        _excluirAutor_arg0Endereco.setEndereco("Endereco1027971588");
        _excluirAutor_arg0Endereco.setId(Integer.valueOf(-749810125));
        _excluirAutor_arg0Endereco.setIdAutor(Integer.valueOf(-1670899027));
        _excluirAutor_arg0Endereco.setUf("Uf-28392963");
        _excluirAutor_arg0.setEndereco(_excluirAutor_arg0Endereco);
        _excluirAutor_arg0.setId(Integer.valueOf(1687137953));
        _excluirAutor_arg0.setNome("Nome-1076483556");
        _excluirAutor_arg0.setNomeCitacao("NomeCitacao-1372086871");
        int _excluirAutor__return = port.excluirAutor(_excluirAutor_arg0);
        System.out.println("excluirAutor.result=" + _excluirAutor__return);


        }
        {
        System.out.println("Invoking excluirPublicacao...");
        int _excluirPublicacao_arg0 = -1384731592;
        int _excluirPublicacao__return = port.excluirPublicacao(_excluirPublicacao_arg0);
        System.out.println("excluirPublicacao.result=" + _excluirPublicacao__return);


        }
        {
        System.out.println("Invoking inserirAutor...");
        br.com.publicacao.webservice.Autor _inserirAutor_arg0 = new br.com.publicacao.webservice.Autor();
        _inserirAutor_arg0.setCpf("Cpf2067835888");
        br.com.publicacao.webservice.Endereco _inserirAutor_arg0Endereco = new br.com.publicacao.webservice.Endereco();
        _inserirAutor_arg0Endereco.setBairro("Bairro-1500548289");
        _inserirAutor_arg0Endereco.setCep(Integer.valueOf(1013244534));
        _inserirAutor_arg0Endereco.setCidade("Cidade2026872233");
        _inserirAutor_arg0Endereco.setEndereco("Endereco-1467651589");
        _inserirAutor_arg0Endereco.setId(Integer.valueOf(1229982680));
        _inserirAutor_arg0Endereco.setIdAutor(Integer.valueOf(159539260));
        _inserirAutor_arg0Endereco.setUf("Uf-127615912");
        _inserirAutor_arg0.setEndereco(_inserirAutor_arg0Endereco);
        _inserirAutor_arg0.setId(Integer.valueOf(-1747855943));
        _inserirAutor_arg0.setNome("Nome-1071493868");
        _inserirAutor_arg0.setNomeCitacao("NomeCitacao1047753307");
        int _inserirAutor__return = port.inserirAutor(_inserirAutor_arg0);
        System.out.println("inserirAutor.result=" + _inserirAutor__return);


        }
        {
        System.out.println("Invoking buscarPublicacoes...");
        java.lang.String _buscarPublicacoes_arg0 = "_buscarPublicacoes_arg01830282173";
        br.com.publicacao.webservice.Publicacao _buscarPublicacoes__return = port.buscarPublicacoes(_buscarPublicacoes_arg0);
        System.out.println("buscarPublicacoes.result=" + _buscarPublicacoes__return);


        }
        {
        System.out.println("Invoking buscarAutor...");
        java.lang.String _buscarAutor_arg0 = "_buscarAutor_arg0919185844";
        br.com.publicacao.webservice.Autor _buscarAutor__return = port.buscarAutor(_buscarAutor_arg0);
        System.out.println("buscarAutor.result=" + _buscarAutor__return);


        }
        {
        System.out.println("Invoking alterarAutor...");
        br.com.publicacao.webservice.Autor _alterarAutor_arg0 = new br.com.publicacao.webservice.Autor();
        _alterarAutor_arg0.setCpf("Cpf-630227737");
        br.com.publicacao.webservice.Endereco _alterarAutor_arg0Endereco = new br.com.publicacao.webservice.Endereco();
        _alterarAutor_arg0Endereco.setBairro("Bairro-208241745");
        _alterarAutor_arg0Endereco.setCep(Integer.valueOf(2112995514));
        _alterarAutor_arg0Endereco.setCidade("Cidade-1503032085");
        _alterarAutor_arg0Endereco.setEndereco("Endereco-244134627");
        _alterarAutor_arg0Endereco.setId(Integer.valueOf(-1688765932));
        _alterarAutor_arg0Endereco.setIdAutor(Integer.valueOf(-1094502198));
        _alterarAutor_arg0Endereco.setUf("Uf-865551367");
        _alterarAutor_arg0.setEndereco(_alterarAutor_arg0Endereco);
        _alterarAutor_arg0.setId(Integer.valueOf(-1309362257));
        _alterarAutor_arg0.setNome("Nome827969068");
        _alterarAutor_arg0.setNomeCitacao("NomeCitacao1863946363");
        int _alterarAutor__return = port.alterarAutor(_alterarAutor_arg0);
        System.out.println("alterarAutor.result=" + _alterarAutor__return);


        }
        {
        System.out.println("Invoking isCPF...");
        java.lang.String _isCPF_arg0 = "_isCPF_arg0111779957";
        boolean _isCPF__return = port.isCPF(_isCPF_arg0);
        System.out.println("isCPF.result=" + _isCPF__return);


        }
        {
        System.out.println("Invoking inserirPublicacao...");
        br.com.publicacao.webservice.Publicacao _inserirPublicacao_arg0 = new br.com.publicacao.webservice.Publicacao();
        _inserirPublicacao_arg0.setDataPublicacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-17T12:33:41.043-03:00"));
        _inserirPublicacao_arg0.setId(Integer.valueOf(-210809769));
        _inserirPublicacao_arg0.setPagFinal(Integer.valueOf(1326463839));
        _inserirPublicacao_arg0.setPagInicial(Integer.valueOf(1252656409));
        _inserirPublicacao_arg0.setTitulo("Titulo1595013788");
        int _inserirPublicacao__return = port.inserirPublicacao(_inserirPublicacao_arg0);
        System.out.println("inserirPublicacao.result=" + _inserirPublicacao__return);


        }
        {
        System.out.println("Invoking alterarPublicacao...");
        br.com.publicacao.webservice.Publicacao _alterarPublicacao_arg0 = new br.com.publicacao.webservice.Publicacao();
        _alterarPublicacao_arg0.setDataPublicacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-17T12:33:41.046-03:00"));
        _alterarPublicacao_arg0.setId(Integer.valueOf(-1682881690));
        _alterarPublicacao_arg0.setPagFinal(Integer.valueOf(-830053341));
        _alterarPublicacao_arg0.setPagInicial(Integer.valueOf(1701891499));
        _alterarPublicacao_arg0.setTitulo("Titulo-1735818963");
        int _alterarPublicacao__return = port.alterarPublicacao(_alterarPublicacao_arg0);
        System.out.println("alterarPublicacao.result=" + _alterarPublicacao__return);


        }

        System.exit(0);
    }

}
