
package br.com.publicaco.correios;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2017-04-13T13:15:54.311-03:00
 * Generated source version: 2.7.16
 * 
 */
public final class AtendeCliente_AtendeClientePort_Client {

    private static final QName SERVICE_NAME = new QName("http://cliente.bean.master.sigep.bsb.correios.com.br/", "AtendeClienteService");

    private AtendeCliente_AtendeClientePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AtendeClienteService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AtendeClienteService ss = new AtendeClienteService(wsdlURL, SERVICE_NAME);
        AtendeCliente port = ss.getAtendeClientePort();  
        
        {
        System.out.println("Invoking fechaPlp...");
        java.lang.String _fechaPlp_xml = "_fechaPlp_xml-1796824834";
        java.lang.Long _fechaPlp_idPlpCliente = Long.valueOf(-314238925702999414l);
        java.lang.String _fechaPlp_cartaoPostagem = "_fechaPlp_cartaoPostagem358673216";
        java.lang.String _fechaPlp_faixaEtiquetas = "_fechaPlp_faixaEtiquetas30712407";
        java.lang.String _fechaPlp_usuario = "_fechaPlp_usuario560906895";
        java.lang.String _fechaPlp_senha = "_fechaPlp_senha1659086906";
        try {
            java.lang.Long _fechaPlp__return = port.fechaPlp(_fechaPlp_xml, _fechaPlp_idPlpCliente, _fechaPlp_cartaoPostagem, _fechaPlp_faixaEtiquetas, _fechaPlp_usuario, _fechaPlp_senha);
            System.out.println("fechaPlp.result=" + _fechaPlp__return);

        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking registrarPedidosInformacao...");
        java.util.List<br.com.publicaco.correios.PedidoInformacaoRegistro> _registrarPedidosInformacao_pedidosInformacao = new java.util.ArrayList<br.com.publicaco.correios.PedidoInformacaoRegistro>();
        br.com.publicaco.correios.PedidoInformacaoRegistro _registrarPedidosInformacao_pedidosInformacaoVal1 = new br.com.publicaco.correios.PedidoInformacaoRegistro();
        _registrarPedidosInformacao_pedidosInformacaoVal1.setId(Long.valueOf(9132716630917159598l));
        _registrarPedidosInformacao_pedidosInformacaoVal1.setUsuario("Usuario-1679467361");
        br.com.publicaco.correios.Cliente _registrarPedidosInformacao_pedidosInformacaoVal1Cliente = new br.com.publicaco.correios.Cliente();
        _registrarPedidosInformacao_pedidosInformacaoVal1Cliente.setNumeroContrato("NumeroContrato1355771045");
        _registrarPedidosInformacao_pedidosInformacaoVal1Cliente.setPossuiContrato("PossuiContrato1586608252");
        _registrarPedidosInformacao_pedidosInformacaoVal1.setCliente(_registrarPedidosInformacao_pedidosInformacaoVal1Cliente);
        _registrarPedidosInformacao_pedidosInformacaoVal1.setCodigoRegistro("CodigoRegistro203443050");
        br.com.publicaco.correios.Conta _registrarPedidosInformacao_pedidosInformacaoVal1Conta = new br.com.publicaco.correios.Conta();
        _registrarPedidosInformacao_pedidosInformacaoVal1Conta.setCodigoBanco("CodigoBanco-1345150256");
        _registrarPedidosInformacao_pedidosInformacaoVal1Conta.setNomeBanco("NomeBanco1009679811");
        _registrarPedidosInformacao_pedidosInformacaoVal1Conta.setNumeroAgencia("NumeroAgencia-1401043070");
        _registrarPedidosInformacao_pedidosInformacaoVal1Conta.setNumeroConta("NumeroConta493543542");
        _registrarPedidosInformacao_pedidosInformacaoVal1.setConta(_registrarPedidosInformacao_pedidosInformacaoVal1Conta);
        _registrarPedidosInformacao_pedidosInformacaoVal1.setConteudoObjeto("ConteudoObjeto535893450");
        _registrarPedidosInformacao_pedidosInformacaoVal1.setCpfCnpj("CpfCnpj-304707106");
        br.com.publicaco.correios.Destinatario _registrarPedidosInformacao_pedidosInformacaoVal1Destinatario = new br.com.publicaco.correios.Destinatario();
        _registrarPedidosInformacao_pedidosInformacaoVal1Destinatario.setBairro("Bairro2043994421");
        _registrarPedidosInformacao_pedidosInformacaoVal1Destinatario.setCep("Cep-1779348172");
        _registrarPedidosInformacao_pedidosInformacaoVal1Destinatario.setCidade("Cidade792807290");
        _registrarPedidosInformacao_pedidosInformacaoVal1Destinatario.setComplemento("Complemento-667240531");
        _registrarPedidosInformacao_pedidosInformacaoVal1Destinatario.setDdd("Ddd279683239");
        _registrarPedidosInformacao_pedidosInformacaoVal1Destinatario.setEndereco("Endereco1013515441");
        _registrarPedidosInformacao_pedidosInformacaoVal1Destinatario.setNome("Nome94830901");
        _registrarPedidosInformacao_pedidosInformacaoVal1Destinatario.setNumero("Numero2143894434");
        _registrarPedidosInformacao_pedidosInformacaoVal1Destinatario.setPais("Pais-112557571");
        _registrarPedidosInformacao_pedidosInformacaoVal1Destinatario.setTelefone("Telefone1040285977");
        _registrarPedidosInformacao_pedidosInformacaoVal1Destinatario.setUf("Uf-105895901");
        _registrarPedidosInformacao_pedidosInformacaoVal1.setDestinatario(_registrarPedidosInformacao_pedidosInformacaoVal1Destinatario);
        _registrarPedidosInformacao_pedidosInformacaoVal1.setEmbalagem("Embalagem-637768064");
        _registrarPedidosInformacao_pedidosInformacaoVal1.setMotivo(Integer.valueOf(-148015242));
        _registrarPedidosInformacao_pedidosInformacaoVal1.setObservacao("Observacao1590185580");
        br.com.publicaco.correios.Postagem _registrarPedidosInformacao_pedidosInformacaoVal1Postagem = new br.com.publicaco.correios.Postagem();
        _registrarPedidosInformacao_pedidosInformacaoVal1Postagem.setAgencia("Agencia45810650");
        _registrarPedidosInformacao_pedidosInformacaoVal1Postagem.setAvisoRecebimento("AvisoRecebimento-1571931857");
        _registrarPedidosInformacao_pedidosInformacaoVal1Postagem.setData("Data653871788");
        _registrarPedidosInformacao_pedidosInformacaoVal1Postagem.setLocal("Local-751399823");
        _registrarPedidosInformacao_pedidosInformacaoVal1Postagem.setValorDeclarado("ValorDeclarado-504902839");
        _registrarPedidosInformacao_pedidosInformacaoVal1.setPostagem(_registrarPedidosInformacao_pedidosInformacaoVal1Postagem);
        br.com.publicaco.correios.Remetente _registrarPedidosInformacao_pedidosInformacaoVal1Remetente = new br.com.publicaco.correios.Remetente();
        _registrarPedidosInformacao_pedidosInformacaoVal1Remetente.setBairro("Bairro1742072275");
        _registrarPedidosInformacao_pedidosInformacaoVal1Remetente.setCep("Cep1586449946");
        _registrarPedidosInformacao_pedidosInformacaoVal1Remetente.setCidade("Cidade-138404885");
        _registrarPedidosInformacao_pedidosInformacaoVal1Remetente.setComplemento("Complemento-1331979305");
        _registrarPedidosInformacao_pedidosInformacaoVal1Remetente.setDdd("Ddd-230308326");
        _registrarPedidosInformacao_pedidosInformacaoVal1Remetente.setEndereco("Endereco-1142152483");
        _registrarPedidosInformacao_pedidosInformacaoVal1Remetente.setNome("Nome-1811158262");
        _registrarPedidosInformacao_pedidosInformacaoVal1Remetente.setNumero("Numero655965899");
        _registrarPedidosInformacao_pedidosInformacaoVal1Remetente.setPais("Pais1115614933");
        _registrarPedidosInformacao_pedidosInformacaoVal1Remetente.setTelefone("Telefone-418998594");
        _registrarPedidosInformacao_pedidosInformacaoVal1Remetente.setUf("Uf1174410532");
        _registrarPedidosInformacao_pedidosInformacaoVal1Remetente.setEmail("Email1729519853");
        _registrarPedidosInformacao_pedidosInformacaoVal1Remetente.setEmpresa("Empresa1732733130");
        _registrarPedidosInformacao_pedidosInformacaoVal1Remetente.setFax("Fax716168816");
        _registrarPedidosInformacao_pedidosInformacaoVal1.setRemetente(_registrarPedidosInformacao_pedidosInformacaoVal1Remetente);
        _registrarPedidosInformacao_pedidosInformacaoVal1.setServico(Integer.valueOf(1011075492));
        _registrarPedidosInformacao_pedidosInformacaoVal1.setTipoDocumento("TipoDocumento-1686495122");
        _registrarPedidosInformacao_pedidosInformacao.add(_registrarPedidosInformacao_pedidosInformacaoVal1);
        java.lang.String _registrarPedidosInformacao_usuario = "_registrarPedidosInformacao_usuario991387335";
        java.lang.String _registrarPedidosInformacao_senha = "_registrarPedidosInformacao_senha-255414251";
        try {
            java.util.List<br.com.publicaco.correios.Retorno> _registrarPedidosInformacao__return = port.registrarPedidosInformacao(_registrarPedidosInformacao_pedidosInformacao, _registrarPedidosInformacao_usuario, _registrarPedidosInformacao_senha);
            System.out.println("registrarPedidosInformacao.result=" + _registrarPedidosInformacao__return);

        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking buscaCliente...");
        java.lang.String _buscaCliente_idContrato = "_buscaCliente_idContrato-343658942";
        java.lang.String _buscaCliente_idCartaoPostagem = "_buscaCliente_idCartaoPostagem-1445194492";
        java.lang.String _buscaCliente_usuario = "_buscaCliente_usuario-776998662";
        java.lang.String _buscaCliente_senha = "_buscaCliente_senha-484244986";
        try {
            br.com.publicaco.correios.ClienteERP _buscaCliente__return = port.buscaCliente(_buscaCliente_idContrato, _buscaCliente_idCartaoPostagem, _buscaCliente_usuario, _buscaCliente_senha);
            System.out.println("buscaCliente.result=" + _buscaCliente__return);

        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking validaEtiquetaPLP...");
        java.lang.String _validaEtiquetaPLP_numeroEtiqueta = "_validaEtiquetaPLP_numeroEtiqueta-1259818892";
        java.lang.Long _validaEtiquetaPLP_idPlp = Long.valueOf(4767401438114424192l);
        java.lang.String _validaEtiquetaPLP_usuario = "_validaEtiquetaPLP_usuario2092462547";
        java.lang.String _validaEtiquetaPLP_senha = "_validaEtiquetaPLP_senha167148067";
        try {
            boolean _validaEtiquetaPLP__return = port.validaEtiquetaPLP(_validaEtiquetaPLP_numeroEtiqueta, _validaEtiquetaPLP_idPlp, _validaEtiquetaPLP_usuario, _validaEtiquetaPLP_senha);
            System.out.println("validaEtiquetaPLP.result=" + _validaEtiquetaPLP__return);

        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking verificaDisponibilidadeServico...");
        java.lang.Integer _verificaDisponibilidadeServico_codAdministrativo = Integer.valueOf(793134245);
        java.lang.String _verificaDisponibilidadeServico_numeroServico = "_verificaDisponibilidadeServico_numeroServico1090113083";
        java.lang.String _verificaDisponibilidadeServico_cepOrigem = "_verificaDisponibilidadeServico_cepOrigem29988744";
        java.lang.String _verificaDisponibilidadeServico_cepDestino = "_verificaDisponibilidadeServico_cepDestino-236323422";
        java.lang.String _verificaDisponibilidadeServico_usuario = "_verificaDisponibilidadeServico_usuario786274201";
        java.lang.String _verificaDisponibilidadeServico_senha = "_verificaDisponibilidadeServico_senha88963048";
        try {
            boolean _verificaDisponibilidadeServico__return = port.verificaDisponibilidadeServico(_verificaDisponibilidadeServico_codAdministrativo, _verificaDisponibilidadeServico_numeroServico, _verificaDisponibilidadeServico_cepOrigem, _verificaDisponibilidadeServico_cepDestino, _verificaDisponibilidadeServico_usuario, _verificaDisponibilidadeServico_senha);
            System.out.println("verificaDisponibilidadeServico.result=" + _verificaDisponibilidadeServico__return);

        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getStatusPLP...");
        java.util.List<br.com.publicaco.correios.ObjetoPostal> _getStatusPLP_arg0 = new java.util.ArrayList<br.com.publicaco.correios.ObjetoPostal>();
        br.com.publicaco.correios.ObjetoPostal _getStatusPLP_arg0Val1 = new br.com.publicaco.correios.ObjetoPostal();
        _getStatusPLP_arg0Val1.setCodigoEtiqueta("CodigoEtiqueta-219756238");
        _getStatusPLP_arg0Val1.setDataAtualizacaoCliente(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.486-03:00"));
        _getStatusPLP_arg0Val1.setDataCancelamentoEtiqueta(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.497-03:00"));
        _getStatusPLP_arg0Val1.setDataInclusao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.498-03:00"));
        br.com.publicaco.correios.ObjetoPostalPK _getStatusPLP_arg0Val1ObjetoPostalPK = new br.com.publicaco.correios.ObjetoPostalPK();
        _getStatusPLP_arg0Val1ObjetoPostalPK.setCodigoEtiqueta("CodigoEtiqueta-1719087909");
        _getStatusPLP_arg0Val1ObjetoPostalPK.setPlpNu(3530953491232700015l);
        _getStatusPLP_arg0Val1.setObjetoPostalPK(_getStatusPLP_arg0Val1ObjetoPostalPK);
        _getStatusPLP_arg0Val1.setPlpNu(Long.valueOf(3537316514616913866l));
        br.com.publicaco.correios.PreListaPostagem _getStatusPLP_arg0Val1PreListaPostagem = new br.com.publicaco.correios.PreListaPostagem();
        br.com.publicaco.correios.CartaoPostagemERP _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem = new br.com.publicaco.correios.CartaoPostagemERP();
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setCodigoAdministrativo("CodigoAdministrativo-2145229666");
        java.util.List<br.com.publicaco.correios.ContratoERP> _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagemContratos = new java.util.ArrayList<br.com.publicaco.correios.ContratoERP>();
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.getContratos().addAll(_getStatusPLP_arg0Val1PreListaPostagemCartaoPostagemContratos);
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.499-03:00"));
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setDataVigenciaFim(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.500-03:00"));
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setDataVigenciaInicio(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.500-03:00"));
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setDatajAtualizacao(Integer.valueOf(-520002947));
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setDatajVigenciaFim(Integer.valueOf(1244816750));
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setDatajVigenciaInicio(Integer.valueOf(-1016058321));
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setDescricaoStatusCartao("DescricaoStatusCartao1769402594");
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setDescricaoUnidadePostagemGenerica("DescricaoUnidadePostagemGenerica-723936177");
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setHorajAtualizacao(Integer.valueOf(526402879));
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setNumero("Numero-1951530881");
        java.util.List<br.com.publicaco.correios.ServicoERP> _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagemServicos = new java.util.ArrayList<br.com.publicaco.correios.ServicoERP>();
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.getServicos().addAll(_getStatusPLP_arg0Val1PreListaPostagemCartaoPostagemServicos);
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setStatusCartaoPostagem("StatusCartaoPostagem-484372548");
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setStatusCodigo("StatusCodigo-398088239");
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.setUnidadeGenerica("UnidadeGenerica756970569");
        java.util.List<br.com.publicaco.correios.UnidadePostagemERP> _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagemUnidadesPostagem = new java.util.ArrayList<br.com.publicaco.correios.UnidadePostagemERP>();
        _getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem.getUnidadesPostagem().addAll(_getStatusPLP_arg0Val1PreListaPostagemCartaoPostagemUnidadesPostagem);
        _getStatusPLP_arg0Val1PreListaPostagem.setCartaoPostagem(_getStatusPLP_arg0Val1PreListaPostagemCartaoPostagem);
        _getStatusPLP_arg0Val1PreListaPostagem.setDataAtualizacaoCliente(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.501-03:00"));
        _getStatusPLP_arg0Val1PreListaPostagem.setDataAtualizacaoSara(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.502-03:00"));
        _getStatusPLP_arg0Val1PreListaPostagem.setDataFechamento(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.503-03:00"));
        _getStatusPLP_arg0Val1PreListaPostagem.setDataPostagem(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.503-03:00"));
        _getStatusPLP_arg0Val1PreListaPostagem.setDataPostagemSara(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.504-03:00"));
        java.util.List<br.com.publicaco.correios.ObjetoPostal> _getStatusPLP_arg0Val1PreListaPostagemObjetosPostais = new java.util.ArrayList<br.com.publicaco.correios.ObjetoPostal>();
        _getStatusPLP_arg0Val1PreListaPostagem.getObjetosPostais().addAll(_getStatusPLP_arg0Val1PreListaPostagemObjetosPostais);
        _getStatusPLP_arg0Val1PreListaPostagem.setPlpCliente(4930346593735737415l);
        _getStatusPLP_arg0Val1PreListaPostagem.setPlpNu(-2203397220980005866l);
        java.util.List<java.lang.Integer> _getStatusPLP_arg0Val1PreListaPostagemPlpXml = new java.util.ArrayList<java.lang.Integer>();
        _getStatusPLP_arg0Val1PreListaPostagem.getPlpXml().addAll(_getStatusPLP_arg0Val1PreListaPostagemPlpXml);
        java.util.List<java.lang.Integer> _getStatusPLP_arg0Val1PreListaPostagemPlpXmlRetorno = new java.util.ArrayList<java.lang.Integer>();
        _getStatusPLP_arg0Val1PreListaPostagem.getPlpXmlRetorno().addAll(_getStatusPLP_arg0Val1PreListaPostagemPlpXmlRetorno);
        br.com.publicaco.correios.StatusPlp _getStatusPLP_arg0Val1PreListaPostagemStatus = br.com.publicaco.correios.StatusPlp.FECHADA;
        _getStatusPLP_arg0Val1PreListaPostagem.setStatus(_getStatusPLP_arg0Val1PreListaPostagemStatus);
        _getStatusPLP_arg0Val1.setPreListaPostagem(_getStatusPLP_arg0Val1PreListaPostagem);
        br.com.publicaco.correios.StatusObjetoPostal _getStatusPLP_arg0Val1StatusEtiqueta = br.com.publicaco.correios.StatusObjetoPostal.EM_BRANCO;
        _getStatusPLP_arg0Val1.setStatusEtiqueta(_getStatusPLP_arg0Val1StatusEtiqueta);
        _getStatusPLP_arg0.add(_getStatusPLP_arg0Val1);
        java.lang.String _getStatusPLP_arg1 = "_getStatusPLP_arg1-1050546423";
        try {
            br.com.publicaco.correios.StatusPlp _getStatusPLP__return = port.getStatusPLP(_getStatusPLP_arg0, _getStatusPLP_arg1);
            System.out.println("getStatusPLP.result=" + _getStatusPLP__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking bloquearObjeto...");
        java.lang.String _bloquearObjeto_numeroEtiqueta = "_bloquearObjeto_numeroEtiqueta-1614254456";
        java.lang.Long _bloquearObjeto_idPlp = Long.valueOf(4540645804454240710l);
        br.com.publicaco.correios.TipoBloqueio _bloquearObjeto_tipoBloqueio = br.com.publicaco.correios.TipoBloqueio.EXTRAVIO_VAREJO_PRE_INDENIZADO;
        br.com.publicaco.correios.Acao _bloquearObjeto_acao = br.com.publicaco.correios.Acao.DEVOLVIDO_AO_REMETENTE;
        java.lang.String _bloquearObjeto_usuario = "_bloquearObjeto_usuario1434376593";
        java.lang.String _bloquearObjeto_senha = "_bloquearObjeto_senha1174210056";
        try {
            java.lang.String _bloquearObjeto__return = port.bloquearObjeto(_bloquearObjeto_numeroEtiqueta, _bloquearObjeto_idPlp, _bloquearObjeto_tipoBloqueio, _bloquearObjeto_acao, _bloquearObjeto_usuario, _bloquearObjeto_senha);
            System.out.println("bloquearObjeto.result=" + _bloquearObjeto__return);

        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking solicitaEtiquetas...");
        java.lang.String _solicitaEtiquetas_tipoDestinatario = "_solicitaEtiquetas_tipoDestinatario-483179936";
        java.lang.String _solicitaEtiquetas_identificador = "_solicitaEtiquetas_identificador1532818547";
        java.lang.Long _solicitaEtiquetas_idServico = Long.valueOf(8098074279385706142l);
        java.lang.Integer _solicitaEtiquetas_qtdEtiquetas = Integer.valueOf(1600799757);
        java.lang.String _solicitaEtiquetas_usuario = "_solicitaEtiquetas_usuario757707278";
        java.lang.String _solicitaEtiquetas_senha = "_solicitaEtiquetas_senha-1899115948";
        try {
            java.lang.String _solicitaEtiquetas__return = port.solicitaEtiquetas(_solicitaEtiquetas_tipoDestinatario, _solicitaEtiquetas_identificador, _solicitaEtiquetas_idServico, _solicitaEtiquetas_qtdEtiquetas, _solicitaEtiquetas_usuario, _solicitaEtiquetas_senha);
            System.out.println("solicitaEtiquetas.result=" + _solicitaEtiquetas__return);

        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking obterMensagemRetornoPI...");
        try {
            java.util.List<br.com.publicaco.correios.MensagemRetornoPIMaster> _obterMensagemRetornoPI__return = port.obterMensagemRetornoPI();
            System.out.println("obterMensagemRetornoPI.result=" + _obterMensagemRetornoPI__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultarPedidosInformacao...");
        java.util.List<br.com.publicaco.correios.PedidoInformacaoConsulta> _consultarPedidosInformacao_pedidosInformacao = new java.util.ArrayList<br.com.publicaco.correios.PedidoInformacaoConsulta>();
        br.com.publicaco.correios.PedidoInformacaoConsulta _consultarPedidosInformacao_pedidosInformacaoVal1 = new br.com.publicaco.correios.PedidoInformacaoConsulta();
        _consultarPedidosInformacao_pedidosInformacaoVal1.setId(Long.valueOf(-5902745962693665374l));
        _consultarPedidosInformacao_pedidosInformacaoVal1.setUsuario("Usuario-1952728487");
        _consultarPedidosInformacao_pedidosInformacaoVal1.setNumero(Long.valueOf(7925841387897478576l));
        _consultarPedidosInformacao_pedidosInformacao.add(_consultarPedidosInformacao_pedidosInformacaoVal1);
        java.lang.String _consultarPedidosInformacao_usuario = "_consultarPedidosInformacao_usuario-674263081";
        java.lang.String _consultarPedidosInformacao_senha = "_consultarPedidosInformacao_senha-510836502";
        try {
            java.util.List<br.com.publicaco.correios.Retorno> _consultarPedidosInformacao__return = port.consultarPedidosInformacao(_consultarPedidosInformacao_pedidosInformacao, _consultarPedidosInformacao_usuario, _consultarPedidosInformacao_senha);
            System.out.println("consultarPedidosInformacao.result=" + _consultarPedidosInformacao__return);

        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking buscaPagamentoEntrega...");
        java.lang.String _buscaPagamentoEntrega_usuario = "_buscaPagamentoEntrega_usuario-1482682515";
        java.lang.String _buscaPagamentoEntrega_senha = "_buscaPagamentoEntrega_senha-562584083";
        try {
            java.lang.String _buscaPagamentoEntrega__return = port.buscaPagamentoEntrega(_buscaPagamentoEntrega_usuario, _buscaPagamentoEntrega_senha);
            System.out.println("buscaPagamentoEntrega.result=" + _buscaPagamentoEntrega__return);

        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking geraDigitoVerificadorEtiquetas...");
        java.util.List<java.lang.String> _geraDigitoVerificadorEtiquetas_etiquetas = new java.util.ArrayList<java.lang.String>();
        java.lang.String _geraDigitoVerificadorEtiquetas_etiquetasVal1 = "_geraDigitoVerificadorEtiquetas_etiquetasVal149572785";
        _geraDigitoVerificadorEtiquetas_etiquetas.add(_geraDigitoVerificadorEtiquetas_etiquetasVal1);
        java.lang.String _geraDigitoVerificadorEtiquetas_usuario = "_geraDigitoVerificadorEtiquetas_usuario-616790774";
        java.lang.String _geraDigitoVerificadorEtiquetas_senha = "_geraDigitoVerificadorEtiquetas_senha1836326500";
        try {
            java.util.List<java.lang.Integer> _geraDigitoVerificadorEtiquetas__return = port.geraDigitoVerificadorEtiquetas(_geraDigitoVerificadorEtiquetas_etiquetas, _geraDigitoVerificadorEtiquetas_usuario, _geraDigitoVerificadorEtiquetas_senha);
            System.out.println("geraDigitoVerificadorEtiquetas.result=" + _geraDigitoVerificadorEtiquetas__return);

        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking cancelarObjeto...");
        java.lang.Long _cancelarObjeto_idPlp = Long.valueOf(6482601826608397007l);
        java.lang.String _cancelarObjeto_numeroEtiqueta = "_cancelarObjeto_numeroEtiqueta1290663027";
        java.lang.String _cancelarObjeto_usuario = "_cancelarObjeto_usuario1816430256";
        java.lang.String _cancelarObjeto_senha = "_cancelarObjeto_senha-1295433822";
        try {
            java.lang.Boolean _cancelarObjeto__return = port.cancelarObjeto(_cancelarObjeto_idPlp, _cancelarObjeto_numeroEtiqueta, _cancelarObjeto_usuario, _cancelarObjeto_senha);
            System.out.println("cancelarObjeto.result=" + _cancelarObjeto__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking fechaPlpVariosServicos...");
        java.lang.String _fechaPlpVariosServicos_xml = "_fechaPlpVariosServicos_xml73390596";
        java.lang.Long _fechaPlpVariosServicos_idPlpCliente = Long.valueOf(-4303411154002254576l);
        java.lang.String _fechaPlpVariosServicos_cartaoPostagem = "_fechaPlpVariosServicos_cartaoPostagem1085932868";
        java.util.List<java.lang.String> _fechaPlpVariosServicos_listaEtiquetas = new java.util.ArrayList<java.lang.String>();
        java.lang.String _fechaPlpVariosServicos_listaEtiquetasVal1 = "_fechaPlpVariosServicos_listaEtiquetasVal-649536219";
        _fechaPlpVariosServicos_listaEtiquetas.add(_fechaPlpVariosServicos_listaEtiquetasVal1);
        java.lang.String _fechaPlpVariosServicos_usuario = "_fechaPlpVariosServicos_usuario-1188994383";
        java.lang.String _fechaPlpVariosServicos_senha = "_fechaPlpVariosServicos_senha1304950759";
        try {
            java.lang.Long _fechaPlpVariosServicos__return = port.fechaPlpVariosServicos(_fechaPlpVariosServicos_xml, _fechaPlpVariosServicos_idPlpCliente, _fechaPlpVariosServicos_cartaoPostagem, _fechaPlpVariosServicos_listaEtiquetas, _fechaPlpVariosServicos_usuario, _fechaPlpVariosServicos_senha);
            System.out.println("fechaPlpVariosServicos.result=" + _fechaPlpVariosServicos__return);

        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking validarPostagemReversa...");
        java.lang.Integer _validarPostagemReversa_codAdministrativo = Integer.valueOf(279763229);
        java.lang.Integer _validarPostagemReversa_codigoServico = Integer.valueOf(-93434589);
        java.lang.String _validarPostagemReversa_cepDestinatario = "_validarPostagemReversa_cepDestinatario-374281818";
        br.com.publicaco.correios.ColetaReversaTO _validarPostagemReversa_coleta = new br.com.publicaco.correios.ColetaReversaTO();
        _validarPostagemReversa_coleta.setCklist("Cklist808700535");
        _validarPostagemReversa_coleta.setDescricao("Descricao-511237060");
        _validarPostagemReversa_coleta.setIdCliente("IdCliente-1675507365");
        java.util.List<br.com.publicaco.correios.ProdutoTO> _validarPostagemReversa_coletaProduto = new java.util.ArrayList<br.com.publicaco.correios.ProdutoTO>();
        br.com.publicaco.correios.ProdutoTO _validarPostagemReversa_coletaProdutoVal1 = new br.com.publicaco.correios.ProdutoTO();
        _validarPostagemReversa_coletaProdutoVal1.setCodigo(Long.valueOf(7982049171555540814l));
        _validarPostagemReversa_coletaProdutoVal1.setQtd(Long.valueOf(3434927026099255596l));
        _validarPostagemReversa_coletaProdutoVal1.setTipo(Long.valueOf(-2895779072007336449l));
        _validarPostagemReversa_coletaProduto.add(_validarPostagemReversa_coletaProdutoVal1);
        _validarPostagemReversa_coleta.getProduto().addAll(_validarPostagemReversa_coletaProduto);
        br.com.publicaco.correios.RemetenteTO _validarPostagemReversa_coletaRemetente = new br.com.publicaco.correios.RemetenteTO();
        _validarPostagemReversa_coletaRemetente.setBairro("Bairro710075232");
        _validarPostagemReversa_coletaRemetente.setCep("Cep1649246922");
        _validarPostagemReversa_coletaRemetente.setCidade("Cidade-1082310470");
        _validarPostagemReversa_coletaRemetente.setComplemento("Complemento846333973");
        _validarPostagemReversa_coletaRemetente.setDdd("Ddd-1011198071");
        _validarPostagemReversa_coletaRemetente.setEmail("Email1658133329");
        _validarPostagemReversa_coletaRemetente.setLogradouro("Logradouro-377881056");
        _validarPostagemReversa_coletaRemetente.setNome("Nome-35473083");
        _validarPostagemReversa_coletaRemetente.setNumero("Numero1859896646");
        _validarPostagemReversa_coletaRemetente.setReferencia("Referencia794952733");
        _validarPostagemReversa_coletaRemetente.setTelefone("Telefone-61815961");
        _validarPostagemReversa_coletaRemetente.setUf("Uf125433570");
        _validarPostagemReversa_coletaRemetente.setIdentificacao("Identificacao-1448881722");
        _validarPostagemReversa_coleta.setRemetente(_validarPostagemReversa_coletaRemetente);
        _validarPostagemReversa_coleta.setTipo("Tipo-1733457576");
        _validarPostagemReversa_coleta.setValorDeclarado("ValorDeclarado937072150");
        _validarPostagemReversa_coleta.setAg("Ag-593939819");
        _validarPostagemReversa_coleta.setAr(Integer.valueOf(-346129113));
        _validarPostagemReversa_coleta.setCartao(Long.valueOf(8328094501963972493l));
        _validarPostagemReversa_coleta.setNumero(Integer.valueOf(-1016781748));
        java.util.List<br.com.publicaco.correios.ObjetoTO> _validarPostagemReversa_coletaObjCol = new java.util.ArrayList<br.com.publicaco.correios.ObjetoTO>();
        br.com.publicaco.correios.ObjetoTO _validarPostagemReversa_coletaObjColVal1 = new br.com.publicaco.correios.ObjetoTO();
        _validarPostagemReversa_coletaObjColVal1.setDesc("Desc-1697663135");
        _validarPostagemReversa_coletaObjColVal1.setEntrega("Entrega1904062489");
        _validarPostagemReversa_coletaObjColVal1.setId("Id1801078417");
        _validarPostagemReversa_coletaObjColVal1.setItem("Item-1324507278");
        _validarPostagemReversa_coletaObjColVal1.setNum("Num407232355");
        _validarPostagemReversa_coletaObjCol.add(_validarPostagemReversa_coletaObjColVal1);
        _validarPostagemReversa_coleta.getObjCol().addAll(_validarPostagemReversa_coletaObjCol);
        _validarPostagemReversa_coleta.setServicoAdicional("ServicoAdicional1974465729");
        java.lang.String _validarPostagemReversa_usuario = "_validarPostagemReversa_usuario348814600";
        java.lang.String _validarPostagemReversa_senha = "_validarPostagemReversa_senha497092449";
        try {
            java.lang.Boolean _validarPostagemReversa__return = port.validarPostagemReversa(_validarPostagemReversa_codAdministrativo, _validarPostagemReversa_codigoServico, _validarPostagemReversa_cepDestinatario, _validarPostagemReversa_coleta, _validarPostagemReversa_usuario, _validarPostagemReversa_senha);
            System.out.println("validarPostagemReversa.result=" + _validarPostagemReversa__return);

        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking validaPlp...");
        long _validaPlp_cliente = -2579840778758135292l;
        java.lang.String _validaPlp_numero = "_validaPlp_numero-64870912";
        long _validaPlp_diretoria = 9024676077908812282l;
        java.lang.String _validaPlp_cartao = "_validaPlp_cartao282298510";
        java.lang.String _validaPlp_unidadePostagem = "_validaPlp_unidadePostagem-2130184203";
        java.lang.Long _validaPlp_servico = Long.valueOf(-4292510846054925033l);
        java.util.List<java.lang.String> _validaPlp_servicosAdicionais = new java.util.ArrayList<java.lang.String>();
        java.lang.String _validaPlp_servicosAdicionaisVal1 = "_validaPlp_servicosAdicionaisVal-1885669992";
        _validaPlp_servicosAdicionais.add(_validaPlp_servicosAdicionaisVal1);
        java.lang.String _validaPlp_usuario = "_validaPlp_usuario-250511533";
        java.lang.String _validaPlp_senha = "_validaPlp_senha-1684298523";
        try {
            boolean _validaPlp__return = port.validaPlp(_validaPlp_cliente, _validaPlp_numero, _validaPlp_diretoria, _validaPlp_cartao, _validaPlp_unidadePostagem, _validaPlp_servico, _validaPlp_servicosAdicionais, _validaPlp_usuario, _validaPlp_senha);
            System.out.println("validaPlp.result=" + _validaPlp__return);

        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking cancelarPedidoScol...");
        java.lang.Integer _cancelarPedidoScol_codAdministrativo = Integer.valueOf(-937087725);
        java.lang.String _cancelarPedidoScol_idPostagem = "_cancelarPedidoScol_idPostagem139061814";
        java.lang.String _cancelarPedidoScol_tipo = "_cancelarPedidoScol_tipo991929657";
        java.lang.String _cancelarPedidoScol_usuario = "_cancelarPedidoScol_usuario322810368";
        java.lang.String _cancelarPedidoScol_senha = "_cancelarPedidoScol_senha-485175906";
        try {
            br.com.publicaco.correios.RetornoCancelamentoTO _cancelarPedidoScol__return = port.cancelarPedidoScol(_cancelarPedidoScol_codAdministrativo, _cancelarPedidoScol_idPostagem, _cancelarPedidoScol_tipo, _cancelarPedidoScol_usuario, _cancelarPedidoScol_senha);
            System.out.println("cancelarPedidoScol.result=" + _cancelarPedidoScol__return);

        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking obterEmbalagemLRS...");
        try {
            java.util.List<br.com.publicaco.correios.EmbalagemLRSMaster> _obterEmbalagemLRS__return = port.obterEmbalagemLRS();
            System.out.println("obterEmbalagemLRS.result=" + _obterEmbalagemLRS__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking validarPostagemSimultanea...");
        java.lang.Integer _validarPostagemSimultanea_codAdministrativo = Integer.valueOf(-2125253651);
        java.lang.Integer _validarPostagemSimultanea_codigoServico = Integer.valueOf(1949720191);
        java.lang.String _validarPostagemSimultanea_cepDestinatario = "_validarPostagemSimultanea_cepDestinatario-895935741";
        br.com.publicaco.correios.ColetaSimultaneaTO _validarPostagemSimultanea_coleta = new br.com.publicaco.correios.ColetaSimultaneaTO();
        _validarPostagemSimultanea_coleta.setCklist("Cklist489864057");
        _validarPostagemSimultanea_coleta.setDescricao("Descricao1230797448");
        _validarPostagemSimultanea_coleta.setIdCliente("IdCliente-1536047366");
        java.util.List<br.com.publicaco.correios.ProdutoTO> _validarPostagemSimultanea_coletaProduto = new java.util.ArrayList<br.com.publicaco.correios.ProdutoTO>();
        br.com.publicaco.correios.ProdutoTO _validarPostagemSimultanea_coletaProdutoVal1 = new br.com.publicaco.correios.ProdutoTO();
        _validarPostagemSimultanea_coletaProdutoVal1.setCodigo(Long.valueOf(-8841377061122200741l));
        _validarPostagemSimultanea_coletaProdutoVal1.setQtd(Long.valueOf(-3597646942917939970l));
        _validarPostagemSimultanea_coletaProdutoVal1.setTipo(Long.valueOf(5427317769709357848l));
        _validarPostagemSimultanea_coletaProduto.add(_validarPostagemSimultanea_coletaProdutoVal1);
        _validarPostagemSimultanea_coleta.getProduto().addAll(_validarPostagemSimultanea_coletaProduto);
        br.com.publicaco.correios.RemetenteTO _validarPostagemSimultanea_coletaRemetente = new br.com.publicaco.correios.RemetenteTO();
        _validarPostagemSimultanea_coletaRemetente.setBairro("Bairro-268187480");
        _validarPostagemSimultanea_coletaRemetente.setCep("Cep-268119773");
        _validarPostagemSimultanea_coletaRemetente.setCidade("Cidade50482997");
        _validarPostagemSimultanea_coletaRemetente.setComplemento("Complemento1502564608");
        _validarPostagemSimultanea_coletaRemetente.setDdd("Ddd-1745331951");
        _validarPostagemSimultanea_coletaRemetente.setEmail("Email-512008628");
        _validarPostagemSimultanea_coletaRemetente.setLogradouro("Logradouro1349617959");
        _validarPostagemSimultanea_coletaRemetente.setNome("Nome-1586406011");
        _validarPostagemSimultanea_coletaRemetente.setNumero("Numero-927496051");
        _validarPostagemSimultanea_coletaRemetente.setReferencia("Referencia2106088933");
        _validarPostagemSimultanea_coletaRemetente.setTelefone("Telefone-1344683721");
        _validarPostagemSimultanea_coletaRemetente.setUf("Uf-949464288");
        _validarPostagemSimultanea_coletaRemetente.setIdentificacao("Identificacao-928001681");
        _validarPostagemSimultanea_coleta.setRemetente(_validarPostagemSimultanea_coletaRemetente);
        _validarPostagemSimultanea_coleta.setTipo("Tipo2033265771");
        _validarPostagemSimultanea_coleta.setValorDeclarado("ValorDeclarado-1245065875");
        _validarPostagemSimultanea_coleta.setObj("Obj-1339717516");
        _validarPostagemSimultanea_coleta.setObs("Obs1456920964");
        java.lang.String _validarPostagemSimultanea_usuario = "_validarPostagemSimultanea_usuario1091711537";
        java.lang.String _validarPostagemSimultanea_senha = "_validarPostagemSimultanea_senha233586355";
        try {
            java.lang.Boolean _validarPostagemSimultanea__return = port.validarPostagemSimultanea(_validarPostagemSimultanea_codAdministrativo, _validarPostagemSimultanea_codigoServico, _validarPostagemSimultanea_cepDestinatario, _validarPostagemSimultanea_coleta, _validarPostagemSimultanea_usuario, _validarPostagemSimultanea_senha);
            System.out.println("validarPostagemSimultanea.result=" + _validarPostagemSimultanea__return);

        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking buscaServicos...");
        java.lang.String _buscaServicos_idContrato = "_buscaServicos_idContrato542931122";
        java.lang.String _buscaServicos_idCartaoPostagem = "_buscaServicos_idCartaoPostagem-830036820";
        java.lang.String _buscaServicos_usuario = "_buscaServicos_usuario-227646368";
        java.lang.String _buscaServicos_senha = "_buscaServicos_senha-600119420";
        try {
            java.util.List<br.com.publicaco.correios.ServicoERP> _buscaServicos__return = port.buscaServicos(_buscaServicos_idContrato, _buscaServicos_idCartaoPostagem, _buscaServicos_usuario, _buscaServicos_senha);
            System.out.println("buscaServicos.result=" + _buscaServicos__return);

        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking solicitarPostagemScol...");
        java.lang.Integer _solicitarPostagemScol_codAdministrativo = Integer.valueOf(-1331112385);
        java.lang.String _solicitarPostagemScol_xml = "_solicitarPostagemScol_xml476241067";
        java.lang.String _solicitarPostagemScol_usuario = "_solicitarPostagemScol_usuario-1362668994";
        java.lang.String _solicitarPostagemScol_senha = "_solicitarPostagemScol_senha592943586";
        try {
            java.lang.String _solicitarPostagemScol__return = port.solicitarPostagemScol(_solicitarPostagemScol_codAdministrativo, _solicitarPostagemScol_xml, _solicitarPostagemScol_usuario, _solicitarPostagemScol_senha);
            System.out.println("solicitarPostagemScol.result=" + _solicitarPostagemScol__return);

        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getStatusCartaoPostagem...");
        java.lang.String _getStatusCartaoPostagem_numeroCartaoPostagem = "_getStatusCartaoPostagem_numeroCartaoPostagem-789535852";
        java.lang.String _getStatusCartaoPostagem_usuario = "_getStatusCartaoPostagem_usuario-72728000";
        java.lang.String _getStatusCartaoPostagem_senha = "_getStatusCartaoPostagem_senha2039628467";
        try {
            br.com.publicaco.correios.StatusCartao _getStatusCartaoPostagem__return = port.getStatusCartaoPostagem(_getStatusCartaoPostagem_numeroCartaoPostagem, _getStatusCartaoPostagem_usuario, _getStatusCartaoPostagem_senha);
            System.out.println("getStatusCartaoPostagem.result=" + _getStatusCartaoPostagem__return);

        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking solicitaPLP...");
        java.lang.Long _solicitaPLP_idPlpMaster = Long.valueOf(-8007874522301303194l);
        java.lang.String _solicitaPLP_numEtiqueta = "_solicitaPLP_numEtiqueta-49964169";
        java.lang.String _solicitaPLP_usuario = "_solicitaPLP_usuario-1780275703";
        java.lang.String _solicitaPLP_senha = "_solicitaPLP_senha-854313103";
        try {
            java.lang.String _solicitaPLP__return = port.solicitaPLP(_solicitaPLP_idPlpMaster, _solicitaPLP_numEtiqueta, _solicitaPLP_usuario, _solicitaPLP_senha);
            System.out.println("solicitaPLP.result=" + _solicitaPLP__return);

        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking solicitaXmlPlp...");
        java.lang.Long _solicitaXmlPlp_idPlpMaster = Long.valueOf(-4954442250896100549l);
        java.lang.String _solicitaXmlPlp_usuario = "_solicitaXmlPlp_usuario-668049421";
        java.lang.String _solicitaXmlPlp_senha = "_solicitaXmlPlp_senha429541215";
        try {
            java.lang.String _solicitaXmlPlp__return = port.solicitaXmlPlp(_solicitaXmlPlp_idPlpMaster, _solicitaXmlPlp_usuario, _solicitaXmlPlp_senha);
            System.out.println("solicitaXmlPlp.result=" + _solicitaXmlPlp__return);

        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking obterMotivosPI...");
        try {
            java.util.List<br.com.publicaco.correios.MotivoPIMaster> _obterMotivosPI__return = port.obterMotivosPI();
            System.out.println("obterMotivosPI.result=" + _obterMotivosPI__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking buscaContrato...");
        java.lang.String _buscaContrato_numero = "_buscaContrato_numero1866563081";
        long _buscaContrato_diretoria = 1990377930073484752l;
        java.lang.String _buscaContrato_usuario = "_buscaContrato_usuario-1845401344";
        java.lang.String _buscaContrato_senha = "_buscaContrato_senha-1702561237";
        try {
            br.com.publicaco.correios.ContratoERP _buscaContrato__return = port.buscaContrato(_buscaContrato_numero, _buscaContrato_diretoria, _buscaContrato_usuario, _buscaContrato_senha);
            System.out.println("buscaContrato.result=" + _buscaContrato__return);

        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaSRO...");
        java.util.List<java.lang.String> _consultaSRO_listaObjetos = new java.util.ArrayList<java.lang.String>();
        java.lang.String _consultaSRO_listaObjetosVal1 = "_consultaSRO_listaObjetosVal-931088195";
        _consultaSRO_listaObjetos.add(_consultaSRO_listaObjetosVal1);
        java.lang.String _consultaSRO_tipoConsulta = "_consultaSRO_tipoConsulta722251056";
        java.lang.String _consultaSRO_tipoResultado = "_consultaSRO_tipoResultado-594980090";
        java.lang.String _consultaSRO_usuarioSro = "_consultaSRO_usuarioSro479885424";
        java.lang.String _consultaSRO_senhaSro = "_consultaSRO_senhaSro2127794798";
        try {
            java.lang.String _consultaSRO__return = port.consultaSRO(_consultaSRO_listaObjetos, _consultaSRO_tipoConsulta, _consultaSRO_tipoResultado, _consultaSRO_usuarioSro, _consultaSRO_senhaSro);
            System.out.println("consultaSRO.result=" + _consultaSRO__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking obterClienteAtualizacao...");
        java.lang.String _obterClienteAtualizacao_cnpjCliente = "_obterClienteAtualizacao_cnpjCliente1144637078";
        java.lang.String _obterClienteAtualizacao_usuario = "_obterClienteAtualizacao_usuario405968803";
        java.lang.String _obterClienteAtualizacao_senha = "_obterClienteAtualizacao_senha1999928460";
        try {
            javax.xml.datatype.XMLGregorianCalendar _obterClienteAtualizacao__return = port.obterClienteAtualizacao(_obterClienteAtualizacao_cnpjCliente, _obterClienteAtualizacao_usuario, _obterClienteAtualizacao_senha);
            System.out.println("obterClienteAtualizacao.result=" + _obterClienteAtualizacao__return);

        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking integrarUsuarioScol...");
        java.lang.Integer _integrarUsuarioScol_codAdministrativo = Integer.valueOf(-939181444);
        java.lang.String _integrarUsuarioScol_usuario = "_integrarUsuarioScol_usuario256409727";
        java.lang.String _integrarUsuarioScol_senha = "_integrarUsuarioScol_senha-1696623298";
        try {
            java.lang.Boolean _integrarUsuarioScol__return = port.integrarUsuarioScol(_integrarUsuarioScol_codAdministrativo, _integrarUsuarioScol_usuario, _integrarUsuarioScol_senha);
            System.out.println("integrarUsuarioScol.result=" + _integrarUsuarioScol__return);

        } catch (AutenticacaoException e) { 
            System.out.println("Expected exception: AutenticacaoException has occurred.");
            System.out.println(e.toString());
        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking obterAssuntosPI...");
        try {
            java.util.List<br.com.publicaco.correios.AssuntoPIMaster> _obterAssuntosPI__return = port.obterAssuntosPI();
            System.out.println("obterAssuntosPI.result=" + _obterAssuntosPI__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaCEP...");
        java.lang.String _consultaCEP_cep = "_consultaCEP_cep1482590084";
        try {
            br.com.publicaco.correios.EnderecoERP _consultaCEP__return = port.consultaCEP(_consultaCEP_cep);
            System.out.println("consultaCEP.result=" + _consultaCEP__return);

        } catch (SigepClienteException e) { 
            System.out.println("Expected exception: SigepClienteException has occurred.");
            System.out.println(e.toString());
        } catch (SQLException_Exception e) { 
            System.out.println("Expected exception: SQLException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
