package br.com.publicaco.correios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2017-04-13T13:15:54.611-03:00
 * Generated source version: 2.7.16
 * 
 */
@WebService(targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", name = "AtendeCliente")
@XmlSeeAlso({ObjectFactory.class})
public interface AtendeCliente {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "fechaPlp", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.FechaPlp")
    @WebMethod
    @ResponseWrapper(localName = "fechaPlpResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.FechaPlpResponse")
    public java.lang.Long fechaPlp(
        @WebParam(name = "xml", targetNamespace = "")
        java.lang.String xml,
        @WebParam(name = "idPlpCliente", targetNamespace = "")
        java.lang.Long idPlpCliente,
        @WebParam(name = "cartaoPostagem", targetNamespace = "")
        java.lang.String cartaoPostagem,
        @WebParam(name = "faixaEtiquetas", targetNamespace = "")
        java.lang.String faixaEtiquetas,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws AutenticacaoException, SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "registrarPedidosInformacao", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.RegistrarPedidosInformacao")
    @WebMethod
    @ResponseWrapper(localName = "registrarPedidosInformacaoResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.RegistrarPedidosInformacaoResponse")
    public java.util.List<br.com.publicaco.correios.Retorno> registrarPedidosInformacao(
        @WebParam(name = "pedidosInformacao", targetNamespace = "")
        java.util.List<br.com.publicaco.correios.PedidoInformacaoRegistro> pedidosInformacao,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws AutenticacaoException, SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "buscaCliente", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.BuscaCliente")
    @WebMethod
    @ResponseWrapper(localName = "buscaClienteResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.BuscaClienteResponse")
    public br.com.publicaco.correios.ClienteERP buscaCliente(
        @WebParam(name = "idContrato", targetNamespace = "")
        java.lang.String idContrato,
        @WebParam(name = "idCartaoPostagem", targetNamespace = "")
        java.lang.String idCartaoPostagem,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws AutenticacaoException, SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "validaEtiquetaPLP", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.ValidaEtiquetaPLP")
    @WebMethod
    @ResponseWrapper(localName = "validaEtiquetaPLPResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.ValidaEtiquetaPLPResponse")
    public boolean validaEtiquetaPLP(
        @WebParam(name = "numeroEtiqueta", targetNamespace = "")
        java.lang.String numeroEtiqueta,
        @WebParam(name = "idPlp", targetNamespace = "")
        java.lang.Long idPlp,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws AutenticacaoException, SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "verificaDisponibilidadeServico", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.VerificaDisponibilidadeServico")
    @WebMethod
    @ResponseWrapper(localName = "verificaDisponibilidadeServicoResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.VerificaDisponibilidadeServicoResponse")
    public boolean verificaDisponibilidadeServico(
        @WebParam(name = "codAdministrativo", targetNamespace = "")
        java.lang.Integer codAdministrativo,
        @WebParam(name = "numeroServico", targetNamespace = "")
        java.lang.String numeroServico,
        @WebParam(name = "cepOrigem", targetNamespace = "")
        java.lang.String cepOrigem,
        @WebParam(name = "cepDestino", targetNamespace = "")
        java.lang.String cepDestino,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws AutenticacaoException, SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getStatusPLP", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.GetStatusPLP")
    @WebMethod
    @ResponseWrapper(localName = "getStatusPLPResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.GetStatusPLPResponse")
    public br.com.publicaco.correios.StatusPlp getStatusPLP(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<br.com.publicaco.correios.ObjetoPostal> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "bloquearObjeto", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.BloquearObjeto")
    @WebMethod
    @ResponseWrapper(localName = "bloquearObjetoResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.BloquearObjetoResponse")
    public java.lang.String bloquearObjeto(
        @WebParam(name = "numeroEtiqueta", targetNamespace = "")
        java.lang.String numeroEtiqueta,
        @WebParam(name = "idPlp", targetNamespace = "")
        java.lang.Long idPlp,
        @WebParam(name = "tipoBloqueio", targetNamespace = "")
        br.com.publicaco.correios.TipoBloqueio tipoBloqueio,
        @WebParam(name = "acao", targetNamespace = "")
        br.com.publicaco.correios.Acao acao,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws AutenticacaoException, SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "solicitaEtiquetas", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.SolicitaEtiquetas")
    @WebMethod
    @ResponseWrapper(localName = "solicitaEtiquetasResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.SolicitaEtiquetasResponse")
    public java.lang.String solicitaEtiquetas(
        @WebParam(name = "tipoDestinatario", targetNamespace = "")
        java.lang.String tipoDestinatario,
        @WebParam(name = "identificador", targetNamespace = "")
        java.lang.String identificador,
        @WebParam(name = "idServico", targetNamespace = "")
        java.lang.Long idServico,
        @WebParam(name = "qtdEtiquetas", targetNamespace = "")
        java.lang.Integer qtdEtiquetas,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws AutenticacaoException, SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "obterMensagemRetornoPI", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.ObterMensagemRetornoPI")
    @WebMethod
    @ResponseWrapper(localName = "obterMensagemRetornoPIResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.ObterMensagemRetornoPIResponse")
    public java.util.List<br.com.publicaco.correios.MensagemRetornoPIMaster> obterMensagemRetornoPI() throws SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "consultarPedidosInformacao", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.ConsultarPedidosInformacao")
    @WebMethod
    @ResponseWrapper(localName = "consultarPedidosInformacaoResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.ConsultarPedidosInformacaoResponse")
    public java.util.List<br.com.publicaco.correios.Retorno> consultarPedidosInformacao(
        @WebParam(name = "pedidosInformacao", targetNamespace = "")
        java.util.List<br.com.publicaco.correios.PedidoInformacaoConsulta> pedidosInformacao,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws AutenticacaoException, SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "buscaPagamentoEntrega", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.BuscaPagamentoEntrega")
    @WebMethod
    @ResponseWrapper(localName = "buscaPagamentoEntregaResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.BuscaPagamentoEntregaResponse")
    public java.lang.String buscaPagamentoEntrega(
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws AutenticacaoException, SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "geraDigitoVerificadorEtiquetas", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.GeraDigitoVerificadorEtiquetas")
    @WebMethod
    @ResponseWrapper(localName = "geraDigitoVerificadorEtiquetasResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.GeraDigitoVerificadorEtiquetasResponse")
    public java.util.List<java.lang.Integer> geraDigitoVerificadorEtiquetas(
        @WebParam(name = "etiquetas", targetNamespace = "")
        java.util.List<java.lang.String> etiquetas,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws AutenticacaoException, SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "cancelarObjeto", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.CancelarObjeto")
    @WebMethod
    @ResponseWrapper(localName = "cancelarObjetoResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.CancelarObjetoResponse")
    public java.lang.Boolean cancelarObjeto(
        @WebParam(name = "idPlp", targetNamespace = "")
        java.lang.Long idPlp,
        @WebParam(name = "numeroEtiqueta", targetNamespace = "")
        java.lang.String numeroEtiqueta,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws Exception_Exception, AutenticacaoException, SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "fechaPlpVariosServicos", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.FechaPlpVariosServicos")
    @WebMethod
    @ResponseWrapper(localName = "fechaPlpVariosServicosResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.FechaPlpVariosServicosResponse")
    public java.lang.Long fechaPlpVariosServicos(
        @WebParam(name = "xml", targetNamespace = "")
        java.lang.String xml,
        @WebParam(name = "idPlpCliente", targetNamespace = "")
        java.lang.Long idPlpCliente,
        @WebParam(name = "cartaoPostagem", targetNamespace = "")
        java.lang.String cartaoPostagem,
        @WebParam(name = "listaEtiquetas", targetNamespace = "")
        java.util.List<java.lang.String> listaEtiquetas,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws AutenticacaoException, SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "validarPostagemReversa", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.ValidarPostagemReversa")
    @WebMethod
    @ResponseWrapper(localName = "validarPostagemReversaResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.ValidarPostagemReversaResponse")
    public java.lang.Boolean validarPostagemReversa(
        @WebParam(name = "codAdministrativo", targetNamespace = "")
        java.lang.Integer codAdministrativo,
        @WebParam(name = "codigoServico", targetNamespace = "")
        java.lang.Integer codigoServico,
        @WebParam(name = "cepDestinatario", targetNamespace = "")
        java.lang.String cepDestinatario,
        @WebParam(name = "coleta", targetNamespace = "")
        br.com.publicaco.correios.ColetaReversaTO coleta,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws AutenticacaoException, SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "validaPlp", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.ValidaPlp")
    @WebMethod
    @ResponseWrapper(localName = "validaPlpResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.ValidaPlpResponse")
    public boolean validaPlp(
        @WebParam(name = "cliente", targetNamespace = "")
        long cliente,
        @WebParam(name = "numero", targetNamespace = "")
        java.lang.String numero,
        @WebParam(name = "diretoria", targetNamespace = "")
        long diretoria,
        @WebParam(name = "cartao", targetNamespace = "")
        java.lang.String cartao,
        @WebParam(name = "unidadePostagem", targetNamespace = "")
        java.lang.String unidadePostagem,
        @WebParam(name = "servico", targetNamespace = "")
        java.lang.Long servico,
        @WebParam(name = "servicosAdicionais", targetNamespace = "")
        java.util.List<java.lang.String> servicosAdicionais,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws AutenticacaoException, SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "cancelarPedidoScol", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.CancelarPedidoScol")
    @WebMethod
    @ResponseWrapper(localName = "cancelarPedidoScolResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.CancelarPedidoScolResponse")
    public br.com.publicaco.correios.RetornoCancelamentoTO cancelarPedidoScol(
        @WebParam(name = "codAdministrativo", targetNamespace = "")
        java.lang.Integer codAdministrativo,
        @WebParam(name = "idPostagem", targetNamespace = "")
        java.lang.String idPostagem,
        @WebParam(name = "tipo", targetNamespace = "")
        java.lang.String tipo,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws AutenticacaoException, SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "obterEmbalagemLRS", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.ObterEmbalagemLRS")
    @WebMethod
    @ResponseWrapper(localName = "obterEmbalagemLRSResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.ObterEmbalagemLRSResponse")
    public java.util.List<br.com.publicaco.correios.EmbalagemLRSMaster> obterEmbalagemLRS() throws SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "validarPostagemSimultanea", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.ValidarPostagemSimultanea")
    @WebMethod
    @ResponseWrapper(localName = "validarPostagemSimultaneaResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.ValidarPostagemSimultaneaResponse")
    public java.lang.Boolean validarPostagemSimultanea(
        @WebParam(name = "codAdministrativo", targetNamespace = "")
        java.lang.Integer codAdministrativo,
        @WebParam(name = "codigoServico", targetNamespace = "")
        java.lang.Integer codigoServico,
        @WebParam(name = "cepDestinatario", targetNamespace = "")
        java.lang.String cepDestinatario,
        @WebParam(name = "coleta", targetNamespace = "")
        br.com.publicaco.correios.ColetaSimultaneaTO coleta,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws AutenticacaoException, SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "buscaServicos", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.BuscaServicos")
    @WebMethod
    @ResponseWrapper(localName = "buscaServicosResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.BuscaServicosResponse")
    public java.util.List<br.com.publicaco.correios.ServicoERP> buscaServicos(
        @WebParam(name = "idContrato", targetNamespace = "")
        java.lang.String idContrato,
        @WebParam(name = "idCartaoPostagem", targetNamespace = "")
        java.lang.String idCartaoPostagem,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws AutenticacaoException, SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "solicitarPostagemScol", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.SolicitarPostagemScol")
    @WebMethod
    @ResponseWrapper(localName = "solicitarPostagemScolResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.SolicitarPostagemScolResponse")
    public java.lang.String solicitarPostagemScol(
        @WebParam(name = "codAdministrativo", targetNamespace = "")
        java.lang.Integer codAdministrativo,
        @WebParam(name = "xml", targetNamespace = "")
        java.lang.String xml,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws AutenticacaoException, SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getStatusCartaoPostagem", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.GetStatusCartaoPostagem")
    @WebMethod
    @ResponseWrapper(localName = "getStatusCartaoPostagemResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.GetStatusCartaoPostagemResponse")
    public br.com.publicaco.correios.StatusCartao getStatusCartaoPostagem(
        @WebParam(name = "numeroCartaoPostagem", targetNamespace = "")
        java.lang.String numeroCartaoPostagem,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws AutenticacaoException, SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "solicitaPLP", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.SolicitaPLP")
    @WebMethod
    @ResponseWrapper(localName = "solicitaPLPResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.SolicitaPLPResponse")
    public java.lang.String solicitaPLP(
        @WebParam(name = "idPlpMaster", targetNamespace = "")
        java.lang.Long idPlpMaster,
        @WebParam(name = "numEtiqueta", targetNamespace = "")
        java.lang.String numEtiqueta,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws AutenticacaoException, SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "solicitaXmlPlp", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.SolicitaXmlPlp")
    @WebMethod
    @ResponseWrapper(localName = "solicitaXmlPlpResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.SolicitaXmlPlpResponse")
    public java.lang.String solicitaXmlPlp(
        @WebParam(name = "idPlpMaster", targetNamespace = "")
        java.lang.Long idPlpMaster,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws AutenticacaoException, SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "obterMotivosPI", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.ObterMotivosPI")
    @WebMethod
    @ResponseWrapper(localName = "obterMotivosPIResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.ObterMotivosPIResponse")
    public java.util.List<br.com.publicaco.correios.MotivoPIMaster> obterMotivosPI() throws SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "buscaContrato", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.BuscaContrato")
    @WebMethod
    @ResponseWrapper(localName = "buscaContratoResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.BuscaContratoResponse")
    public br.com.publicaco.correios.ContratoERP buscaContrato(
        @WebParam(name = "numero", targetNamespace = "")
        java.lang.String numero,
        @WebParam(name = "diretoria", targetNamespace = "")
        long diretoria,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws AutenticacaoException, SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "consultaSRO", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.ConsultaSRO")
    @WebMethod
    @ResponseWrapper(localName = "consultaSROResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.ConsultaSROResponse")
    public java.lang.String consultaSRO(
        @WebParam(name = "listaObjetos", targetNamespace = "")
        java.util.List<java.lang.String> listaObjetos,
        @WebParam(name = "tipoConsulta", targetNamespace = "")
        java.lang.String tipoConsulta,
        @WebParam(name = "tipoResultado", targetNamespace = "")
        java.lang.String tipoResultado,
        @WebParam(name = "usuarioSro", targetNamespace = "")
        java.lang.String usuarioSro,
        @WebParam(name = "senhaSro", targetNamespace = "")
        java.lang.String senhaSro
    ) throws SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "obterClienteAtualizacao", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.ObterClienteAtualizacao")
    @WebMethod
    @ResponseWrapper(localName = "obterClienteAtualizacaoResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.ObterClienteAtualizacaoResponse")
    public javax.xml.datatype.XMLGregorianCalendar obterClienteAtualizacao(
        @WebParam(name = "cnpjCliente", targetNamespace = "")
        java.lang.String cnpjCliente,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws AutenticacaoException, SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "integrarUsuarioScol", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.IntegrarUsuarioScol")
    @WebMethod
    @ResponseWrapper(localName = "integrarUsuarioScolResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.IntegrarUsuarioScolResponse")
    public java.lang.Boolean integrarUsuarioScol(
        @WebParam(name = "codAdministrativo", targetNamespace = "")
        java.lang.Integer codAdministrativo,
        @WebParam(name = "usuario", targetNamespace = "")
        java.lang.String usuario,
        @WebParam(name = "senha", targetNamespace = "")
        java.lang.String senha
    ) throws AutenticacaoException, SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "obterAssuntosPI", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.ObterAssuntosPI")
    @WebMethod
    @ResponseWrapper(localName = "obterAssuntosPIResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.ObterAssuntosPIResponse")
    public java.util.List<br.com.publicaco.correios.AssuntoPIMaster> obterAssuntosPI() throws SigepClienteException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "consultaCEP", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.ConsultaCEP")
    @WebMethod
    @ResponseWrapper(localName = "consultaCEPResponse", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/", className = "br.com.publicaco.correios.ConsultaCEPResponse")
    public br.com.publicaco.correios.EnderecoERP consultaCEP(
        @WebParam(name = "cep", targetNamespace = "")
        java.lang.String cep
    ) throws SigepClienteException, SQLException_Exception;
}
