
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package br.com.publicaco.correios;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2017-04-13T13:15:54.555-03:00
 * Generated source version: 2.7.16
 * 
 */

@javax.jws.WebService(
                      serviceName = "AtendeClienteService",
                      portName = "AtendeClientePort",
                      targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/",
                      wsdlLocation = "https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente?wsdl",
                      endpointInterface = "br.com.publicaco.correios.AtendeCliente")
                      
public class AtendeClienteImpl implements AtendeCliente {

    private static final Logger LOG = Logger.getLogger(AtendeClienteImpl.class.getName());

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#fechaPlp(java.lang.String  xml ,)java.lang.Long  idPlpCliente ,)java.lang.String  cartaoPostagem ,)java.lang.String  faixaEtiquetas ,)java.lang.String  usuario ,)java.lang.String  senha )*
     */
    public java.lang.Long fechaPlp(java.lang.String xml,java.lang.Long idPlpCliente,java.lang.String cartaoPostagem,java.lang.String faixaEtiquetas,java.lang.String usuario,java.lang.String senha) throws AutenticacaoException , SigepClienteException    { 
        LOG.info("Executing operation fechaPlp");
        System.out.println(xml);
        System.out.println(idPlpCliente);
        System.out.println(cartaoPostagem);
        System.out.println(faixaEtiquetas);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.lang.Long _return = Long.valueOf(2184775394033958563l);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AutenticacaoException("AutenticacaoException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#registrarPedidosInformacao(java.util.List<br.com.publicaco.correios.PedidoInformacaoRegistro>  pedidosInformacao ,)java.lang.String  usuario ,)java.lang.String  senha )*
     */
    public java.util.List<br.com.publicaco.correios.Retorno> registrarPedidosInformacao(java.util.List<br.com.publicaco.correios.PedidoInformacaoRegistro> pedidosInformacao,java.lang.String usuario,java.lang.String senha) throws AutenticacaoException , SigepClienteException    { 
        LOG.info("Executing operation registrarPedidosInformacao");
        System.out.println(pedidosInformacao);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.util.List<br.com.publicaco.correios.Retorno> _return = new java.util.ArrayList<br.com.publicaco.correios.Retorno>();
            br.com.publicaco.correios.Retorno _returnVal1 = new br.com.publicaco.correios.Retorno();
            _returnVal1.setCodigoPI(Long.valueOf(-3042394424384327020l));
            _returnVal1.setCodigoRegistro("CodigoRegistro-1490549439");
            _returnVal1.setCodigoRetorno("CodigoRetorno1338814842");
            _returnVal1.setDataPrazoResposta("DataPrazoResposta-482874116");
            _returnVal1.setDataRegistro("DataRegistro221779027");
            _returnVal1.setDataResposta("DataResposta-1211033706");
            _returnVal1.setDataUltimaRecorrencia("DataUltimaRecorrencia-1272546815");
            _returnVal1.setId(Long.valueOf(-5343603705615313900l));
            _returnVal1.setMensagemRetorno("MensagemRetorno898357611");
            _returnVal1.setResposta("Resposta885573053");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AutenticacaoException("AutenticacaoException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#buscaCliente(java.lang.String  idContrato ,)java.lang.String  idCartaoPostagem ,)java.lang.String  usuario ,)java.lang.String  senha )*
     */
    public br.com.publicaco.correios.ClienteERP buscaCliente(java.lang.String idContrato,java.lang.String idCartaoPostagem,java.lang.String usuario,java.lang.String senha) throws AutenticacaoException , SigepClienteException    { 
        LOG.info("Executing operation buscaCliente");
        System.out.println(idContrato);
        System.out.println(idCartaoPostagem);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            br.com.publicaco.correios.ClienteERP _return = new br.com.publicaco.correios.ClienteERP();
            _return.setCnpj("Cnpj846391526");
            java.util.List<br.com.publicaco.correios.ContratoERP> _returnContratos = new java.util.ArrayList<br.com.publicaco.correios.ContratoERP>();
            br.com.publicaco.correios.ContratoERP _returnContratosVal1 = new br.com.publicaco.correios.ContratoERP();
            java.util.List<br.com.publicaco.correios.CartaoPostagemERP> _returnContratosVal1CartoesPostagem = new java.util.ArrayList<br.com.publicaco.correios.CartaoPostagemERP>();
            _returnContratosVal1.getCartoesPostagem().addAll(_returnContratosVal1CartoesPostagem);
            br.com.publicaco.correios.ClienteERP _returnContratosVal1Cliente = new br.com.publicaco.correios.ClienteERP();
            _returnContratosVal1Cliente.setCnpj("Cnpj1195970447");
            java.util.List<br.com.publicaco.correios.ContratoERP> _returnContratosVal1ClienteContratos = new java.util.ArrayList<br.com.publicaco.correios.ContratoERP>();
            _returnContratosVal1Cliente.getContratos().addAll(_returnContratosVal1ClienteContratos);
            _returnContratosVal1Cliente.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.566-03:00"));
            _returnContratosVal1Cliente.setDatajAtualizacao(Integer.valueOf(-268814118));
            _returnContratosVal1Cliente.setDescricaoStatusCliente("DescricaoStatusCliente2098358016");
            java.util.List<br.com.publicaco.correios.GerenteConta> _returnContratosVal1ClienteGerenteConta = new java.util.ArrayList<br.com.publicaco.correios.GerenteConta>();
            _returnContratosVal1Cliente.getGerenteConta().addAll(_returnContratosVal1ClienteGerenteConta);
            _returnContratosVal1Cliente.setHorajAtualizacao(Long.valueOf(3549057662898697921l));
            _returnContratosVal1Cliente.setId(4651595449242692970l);
            _returnContratosVal1Cliente.setInscricaoEstadual("InscricaoEstadual898730453");
            _returnContratosVal1Cliente.setNome("Nome386843152");
            _returnContratosVal1Cliente.setStatusCodigo("StatusCodigo-793040548");
            _returnContratosVal1.setCliente(_returnContratosVal1Cliente);
            _returnContratosVal1.setCodigoCliente(2104169151027751800l);
            _returnContratosVal1.setCodigoDiretoria("CodigoDiretoria-1638799695");
            br.com.publicaco.correios.ContratoERPPK _returnContratosVal1ContratoPK = new br.com.publicaco.correios.ContratoERPPK();
            _returnContratosVal1ContratoPK.setDiretoria(5507313300256231334l);
            _returnContratosVal1ContratoPK.setNumero("Numero-1036659366");
            _returnContratosVal1.setContratoPK(_returnContratosVal1ContratoPK);
            _returnContratosVal1.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.567-03:00"));
            _returnContratosVal1.setDataAtualizacaoDDMMYYYY("DataAtualizacaoDDMMYYYY-239129266");
            _returnContratosVal1.setDataVigenciaFim(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.568-03:00"));
            _returnContratosVal1.setDataVigenciaFimDDMMYYYY("DataVigenciaFimDDMMYYYY-1413758244");
            _returnContratosVal1.setDataVigenciaInicio(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.569-03:00"));
            _returnContratosVal1.setDataVigenciaInicioDDMMYYYY("DataVigenciaInicioDDMMYYYY806038896");
            _returnContratosVal1.setDatajAtualizacao(Integer.valueOf(-237787244));
            _returnContratosVal1.setDatajVigenciaFim(Integer.valueOf(-789655838));
            _returnContratosVal1.setDatajVigenciaInicio(Integer.valueOf(1869563925));
            _returnContratosVal1.setDescricaoDiretoriaRegional("DescricaoDiretoriaRegional383264538");
            _returnContratosVal1.setDescricaoStatus("DescricaoStatus1723021367");
            br.com.publicaco.correios.UnidadePostagemERP _returnContratosVal1DiretoriaRegional = new br.com.publicaco.correios.UnidadePostagemERP();
            _returnContratosVal1DiretoriaRegional.setDiretoriaRegional("DiretoriaRegional-1899889689");
            br.com.publicaco.correios.EnderecoERP _returnContratosVal1DiretoriaRegionalEndereco = new br.com.publicaco.correios.EnderecoERP();
            _returnContratosVal1DiretoriaRegionalEndereco.setBairro("Bairro-990954642");
            _returnContratosVal1DiretoriaRegionalEndereco.setCep("Cep630493011");
            _returnContratosVal1DiretoriaRegionalEndereco.setCidade("Cidade443363269");
            _returnContratosVal1DiretoriaRegionalEndereco.setComplemento("Complemento1988866483");
            _returnContratosVal1DiretoriaRegionalEndereco.setComplemento2("Complemento2-1198962552");
            _returnContratosVal1DiretoriaRegionalEndereco.setEnd("End-1109053838");
            _returnContratosVal1DiretoriaRegionalEndereco.setId(-1884553163988073953l);
            _returnContratosVal1DiretoriaRegionalEndereco.setUf("Uf-293872648");
            java.util.List<br.com.publicaco.correios.UnidadePostagemERP> _returnContratosVal1DiretoriaRegionalEnderecoUnidadesPostagem = new java.util.ArrayList<br.com.publicaco.correios.UnidadePostagemERP>();
            _returnContratosVal1DiretoriaRegionalEndereco.getUnidadesPostagem().addAll(_returnContratosVal1DiretoriaRegionalEnderecoUnidadesPostagem);
            _returnContratosVal1DiretoriaRegional.setEndereco(_returnContratosVal1DiretoriaRegionalEndereco);
            _returnContratosVal1DiretoriaRegional.setId("Id266620091");
            _returnContratosVal1DiretoriaRegional.setNome("Nome671987530");
            _returnContratosVal1DiretoriaRegional.setStatus("Status1312272745");
            _returnContratosVal1DiretoriaRegional.setTipo("Tipo1686386015");
            _returnContratosVal1.setDiretoriaRegional(_returnContratosVal1DiretoriaRegional);
            _returnContratosVal1.setHorajAtualizacao(Integer.valueOf(709713121));
            _returnContratosVal1.setStatusCodigo("StatusCodigo-1914766843");
            _returnContratos.add(_returnContratosVal1);
            _return.getContratos().addAll(_returnContratos);
            _return.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.570-03:00"));
            _return.setDatajAtualizacao(Integer.valueOf(-29602213));
            _return.setDescricaoStatusCliente("DescricaoStatusCliente1819477687");
            java.util.List<br.com.publicaco.correios.GerenteConta> _returnGerenteConta = new java.util.ArrayList<br.com.publicaco.correios.GerenteConta>();
            br.com.publicaco.correios.GerenteConta _returnGerenteContaVal1 = new br.com.publicaco.correios.GerenteConta();
            java.util.List<br.com.publicaco.correios.ClienteERP> _returnGerenteContaVal1ClientesVisiveis = new java.util.ArrayList<br.com.publicaco.correios.ClienteERP>();
            _returnGerenteContaVal1.getClientesVisiveis().addAll(_returnGerenteContaVal1ClientesVisiveis);
            _returnGerenteContaVal1.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.571-03:00"));
            _returnGerenteContaVal1.setDataInclusao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.572-03:00"));
            _returnGerenteContaVal1.setDataSenha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.572-03:00"));
            _returnGerenteContaVal1.setLogin("Login-329626932");
            _returnGerenteContaVal1.setMatricula("Matricula1988680921");
            _returnGerenteContaVal1.setSenha("Senha-1561909076");
            br.com.publicaco.correios.StatusGerente _returnGerenteContaVal1Status = br.com.publicaco.correios.StatusGerente.INATIVO;
            _returnGerenteContaVal1.setStatus(_returnGerenteContaVal1Status);
            br.com.publicaco.correios.TipoGerente _returnGerenteContaVal1TipoGerente = br.com.publicaco.correios.TipoGerente.GERENTE_CONTA_MASTER;
            _returnGerenteContaVal1.setTipoGerente(_returnGerenteContaVal1TipoGerente);
            java.util.List<br.com.publicaco.correios.UsuarioInstalacao> _returnGerenteContaVal1UsuariosInstalacao = new java.util.ArrayList<br.com.publicaco.correios.UsuarioInstalacao>();
            _returnGerenteContaVal1.getUsuariosInstalacao().addAll(_returnGerenteContaVal1UsuariosInstalacao);
            _returnGerenteContaVal1.setValidade("Validade488901888");
            _returnGerenteConta.add(_returnGerenteContaVal1);
            _return.getGerenteConta().addAll(_returnGerenteConta);
            _return.setHorajAtualizacao(Long.valueOf(-3412099431953887814l));
            _return.setId(-2119080048220478181l);
            _return.setInscricaoEstadual("InscricaoEstadual1754583815");
            _return.setNome("Nome1794999972");
            _return.setStatusCodigo("StatusCodigo-1990929062");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AutenticacaoException("AutenticacaoException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#validaEtiquetaPLP(java.lang.String  numeroEtiqueta ,)java.lang.Long  idPlp ,)java.lang.String  usuario ,)java.lang.String  senha )*
     */
    public boolean validaEtiquetaPLP(java.lang.String numeroEtiqueta,java.lang.Long idPlp,java.lang.String usuario,java.lang.String senha) throws AutenticacaoException , SigepClienteException    { 
        LOG.info("Executing operation validaEtiquetaPLP");
        System.out.println(numeroEtiqueta);
        System.out.println(idPlp);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AutenticacaoException("AutenticacaoException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#verificaDisponibilidadeServico(java.lang.Integer  codAdministrativo ,)java.lang.String  numeroServico ,)java.lang.String  cepOrigem ,)java.lang.String  cepDestino ,)java.lang.String  usuario ,)java.lang.String  senha )*
     */
    public boolean verificaDisponibilidadeServico(java.lang.Integer codAdministrativo,java.lang.String numeroServico,java.lang.String cepOrigem,java.lang.String cepDestino,java.lang.String usuario,java.lang.String senha) throws AutenticacaoException , SigepClienteException    { 
        LOG.info("Executing operation verificaDisponibilidadeServico");
        System.out.println(codAdministrativo);
        System.out.println(numeroServico);
        System.out.println(cepOrigem);
        System.out.println(cepDestino);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AutenticacaoException("AutenticacaoException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#getStatusPLP(java.util.List<br.com.publicaco.correios.ObjetoPostal>  arg0 ,)java.lang.String  arg1 )*
     */
    public br.com.publicaco.correios.StatusPlp getStatusPLP(java.util.List<br.com.publicaco.correios.ObjetoPostal> arg0,java.lang.String arg1) throws SigepClienteException    { 
        LOG.info("Executing operation getStatusPLP");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            br.com.publicaco.correios.StatusPlp _return = br.com.publicaco.correios.StatusPlp.FECHADA;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#bloquearObjeto(java.lang.String  numeroEtiqueta ,)java.lang.Long  idPlp ,)br.com.publicaco.correios.TipoBloqueio  tipoBloqueio ,)br.com.publicaco.correios.Acao  acao ,)java.lang.String  usuario ,)java.lang.String  senha )*
     */
    public java.lang.String bloquearObjeto(java.lang.String numeroEtiqueta,java.lang.Long idPlp,br.com.publicaco.correios.TipoBloqueio tipoBloqueio,br.com.publicaco.correios.Acao acao,java.lang.String usuario,java.lang.String senha) throws AutenticacaoException , SigepClienteException    { 
        LOG.info("Executing operation bloquearObjeto");
        System.out.println(numeroEtiqueta);
        System.out.println(idPlp);
        System.out.println(tipoBloqueio);
        System.out.println(acao);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.lang.String _return = "_return1202318407";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AutenticacaoException("AutenticacaoException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#solicitaEtiquetas(java.lang.String  tipoDestinatario ,)java.lang.String  identificador ,)java.lang.Long  idServico ,)java.lang.Integer  qtdEtiquetas ,)java.lang.String  usuario ,)java.lang.String  senha )*
     */
    public java.lang.String solicitaEtiquetas(java.lang.String tipoDestinatario,java.lang.String identificador,java.lang.Long idServico,java.lang.Integer qtdEtiquetas,java.lang.String usuario,java.lang.String senha) throws AutenticacaoException , SigepClienteException    { 
        LOG.info("Executing operation solicitaEtiquetas");
        System.out.println(tipoDestinatario);
        System.out.println(identificador);
        System.out.println(idServico);
        System.out.println(qtdEtiquetas);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.lang.String _return = "_return-471956180";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AutenticacaoException("AutenticacaoException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#obterMensagemRetornoPI(*
     */
    public java.util.List<br.com.publicaco.correios.MensagemRetornoPIMaster> obterMensagemRetornoPI() throws SigepClienteException    { 
        LOG.info("Executing operation obterMensagemRetornoPI");
        try {
            java.util.List<br.com.publicaco.correios.MensagemRetornoPIMaster> _return = new java.util.ArrayList<br.com.publicaco.correios.MensagemRetornoPIMaster>();
            br.com.publicaco.correios.MensagemRetornoPIMaster _returnVal1 = new br.com.publicaco.correios.MensagemRetornoPIMaster();
            _returnVal1.setCodigo(Integer.valueOf(-265321109));
            _returnVal1.setMensagem("Mensagem650711418");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#consultarPedidosInformacao(java.util.List<br.com.publicaco.correios.PedidoInformacaoConsulta>  pedidosInformacao ,)java.lang.String  usuario ,)java.lang.String  senha )*
     */
    public java.util.List<br.com.publicaco.correios.Retorno> consultarPedidosInformacao(java.util.List<br.com.publicaco.correios.PedidoInformacaoConsulta> pedidosInformacao,java.lang.String usuario,java.lang.String senha) throws AutenticacaoException , SigepClienteException    { 
        LOG.info("Executing operation consultarPedidosInformacao");
        System.out.println(pedidosInformacao);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.util.List<br.com.publicaco.correios.Retorno> _return = new java.util.ArrayList<br.com.publicaco.correios.Retorno>();
            br.com.publicaco.correios.Retorno _returnVal1 = new br.com.publicaco.correios.Retorno();
            _returnVal1.setCodigoPI(Long.valueOf(7709385049953908348l));
            _returnVal1.setCodigoRegistro("CodigoRegistro35318208");
            _returnVal1.setCodigoRetorno("CodigoRetorno882204400");
            _returnVal1.setDataPrazoResposta("DataPrazoResposta-803183029");
            _returnVal1.setDataRegistro("DataRegistro-587072228");
            _returnVal1.setDataResposta("DataResposta-380209492");
            _returnVal1.setDataUltimaRecorrencia("DataUltimaRecorrencia173556354");
            _returnVal1.setId(Long.valueOf(8563435663978749885l));
            _returnVal1.setMensagemRetorno("MensagemRetorno544090714");
            _returnVal1.setResposta("Resposta151316198");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AutenticacaoException("AutenticacaoException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#buscaPagamentoEntrega(java.lang.String  usuario ,)java.lang.String  senha )*
     */
    public java.lang.String buscaPagamentoEntrega(java.lang.String usuario,java.lang.String senha) throws AutenticacaoException , SigepClienteException    { 
        LOG.info("Executing operation buscaPagamentoEntrega");
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.lang.String _return = "_return1073268524";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AutenticacaoException("AutenticacaoException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#geraDigitoVerificadorEtiquetas(java.util.List<java.lang.String>  etiquetas ,)java.lang.String  usuario ,)java.lang.String  senha )*
     */
    public java.util.List<java.lang.Integer> geraDigitoVerificadorEtiquetas(java.util.List<java.lang.String> etiquetas,java.lang.String usuario,java.lang.String senha) throws AutenticacaoException , SigepClienteException    { 
        LOG.info("Executing operation geraDigitoVerificadorEtiquetas");
        System.out.println(etiquetas);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.util.List<java.lang.Integer> _return = new java.util.ArrayList<java.lang.Integer>();
            java.lang.Integer _returnVal1 = Integer.valueOf(1478427248);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AutenticacaoException("AutenticacaoException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#cancelarObjeto(java.lang.Long  idPlp ,)java.lang.String  numeroEtiqueta ,)java.lang.String  usuario ,)java.lang.String  senha )*
     */
    public java.lang.Boolean cancelarObjeto(java.lang.Long idPlp,java.lang.String numeroEtiqueta,java.lang.String usuario,java.lang.String senha) throws Exception_Exception , AutenticacaoException , SigepClienteException    { 
        LOG.info("Executing operation cancelarObjeto");
        System.out.println(idPlp);
        System.out.println(numeroEtiqueta);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.lang.Boolean _return = Boolean.valueOf(true);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
        //throw new AutenticacaoException("AutenticacaoException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#fechaPlpVariosServicos(java.lang.String  xml ,)java.lang.Long  idPlpCliente ,)java.lang.String  cartaoPostagem ,)java.util.List<java.lang.String>  listaEtiquetas ,)java.lang.String  usuario ,)java.lang.String  senha )*
     */
    public java.lang.Long fechaPlpVariosServicos(java.lang.String xml,java.lang.Long idPlpCliente,java.lang.String cartaoPostagem,java.util.List<java.lang.String> listaEtiquetas,java.lang.String usuario,java.lang.String senha) throws AutenticacaoException , SigepClienteException    { 
        LOG.info("Executing operation fechaPlpVariosServicos");
        System.out.println(xml);
        System.out.println(idPlpCliente);
        System.out.println(cartaoPostagem);
        System.out.println(listaEtiquetas);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.lang.Long _return = Long.valueOf(1296257562723094057l);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AutenticacaoException("AutenticacaoException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#validarPostagemReversa(java.lang.Integer  codAdministrativo ,)java.lang.Integer  codigoServico ,)java.lang.String  cepDestinatario ,)br.com.publicaco.correios.ColetaReversaTO  coleta ,)java.lang.String  usuario ,)java.lang.String  senha )*
     */
    public java.lang.Boolean validarPostagemReversa(java.lang.Integer codAdministrativo,java.lang.Integer codigoServico,java.lang.String cepDestinatario,br.com.publicaco.correios.ColetaReversaTO coleta,java.lang.String usuario,java.lang.String senha) throws AutenticacaoException , SigepClienteException    { 
        LOG.info("Executing operation validarPostagemReversa");
        System.out.println(codAdministrativo);
        System.out.println(codigoServico);
        System.out.println(cepDestinatario);
        System.out.println(coleta);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.lang.Boolean _return = Boolean.valueOf(false);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AutenticacaoException("AutenticacaoException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#validaPlp(long  cliente ,)java.lang.String  numero ,)long  diretoria ,)java.lang.String  cartao ,)java.lang.String  unidadePostagem ,)java.lang.Long  servico ,)java.util.List<java.lang.String>  servicosAdicionais ,)java.lang.String  usuario ,)java.lang.String  senha )*
     */
    public boolean validaPlp(long cliente,java.lang.String numero,long diretoria,java.lang.String cartao,java.lang.String unidadePostagem,java.lang.Long servico,java.util.List<java.lang.String> servicosAdicionais,java.lang.String usuario,java.lang.String senha) throws AutenticacaoException , SigepClienteException    { 
        LOG.info("Executing operation validaPlp");
        System.out.println(cliente);
        System.out.println(numero);
        System.out.println(diretoria);
        System.out.println(cartao);
        System.out.println(unidadePostagem);
        System.out.println(servico);
        System.out.println(servicosAdicionais);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AutenticacaoException("AutenticacaoException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#cancelarPedidoScol(java.lang.Integer  codAdministrativo ,)java.lang.String  idPostagem ,)java.lang.String  tipo ,)java.lang.String  usuario ,)java.lang.String  senha )*
     */
    public br.com.publicaco.correios.RetornoCancelamentoTO cancelarPedidoScol(java.lang.Integer codAdministrativo,java.lang.String idPostagem,java.lang.String tipo,java.lang.String usuario,java.lang.String senha) throws AutenticacaoException , SigepClienteException    { 
        LOG.info("Executing operation cancelarPedidoScol");
        System.out.println(codAdministrativo);
        System.out.println(idPostagem);
        System.out.println(tipo);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            br.com.publicaco.correios.RetornoCancelamentoTO _return = new br.com.publicaco.correios.RetornoCancelamentoTO();
            _return.setCodErro("CodErro-1230560345");
            _return.setCodigoAdministrativo("CodigoAdministrativo328854369");
            _return.setData("Data-492438879");
            _return.setHora("Hora1134001546");
            _return.setMsgErro("MsgErro-2105257770");
            br.com.publicaco.correios.ObjetoSimplificadoTO _returnObjetoPostal = new br.com.publicaco.correios.ObjetoSimplificadoTO();
            _returnObjetoPostal.setDatahoraCancelamento("DatahoraCancelamento470249988");
            _returnObjetoPostal.setNumeroPedido(Integer.valueOf(-1636919376));
            _returnObjetoPostal.setStatusPedido("StatusPedido-1669089241");
            _return.setObjetoPostal(_returnObjetoPostal);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AutenticacaoException("AutenticacaoException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#obterEmbalagemLRS(*
     */
    public java.util.List<br.com.publicaco.correios.EmbalagemLRSMaster> obterEmbalagemLRS() throws SigepClienteException    { 
        LOG.info("Executing operation obterEmbalagemLRS");
        try {
            java.util.List<br.com.publicaco.correios.EmbalagemLRSMaster> _return = new java.util.ArrayList<br.com.publicaco.correios.EmbalagemLRSMaster>();
            br.com.publicaco.correios.EmbalagemLRSMaster _returnVal1 = new br.com.publicaco.correios.EmbalagemLRSMaster();
            _returnVal1.setCodigo("Codigo1539708902");
            _returnVal1.setNome("Nome290183973");
            _returnVal1.setTipo("Tipo485033371");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#validarPostagemSimultanea(java.lang.Integer  codAdministrativo ,)java.lang.Integer  codigoServico ,)java.lang.String  cepDestinatario ,)br.com.publicaco.correios.ColetaSimultaneaTO  coleta ,)java.lang.String  usuario ,)java.lang.String  senha )*
     */
    public java.lang.Boolean validarPostagemSimultanea(java.lang.Integer codAdministrativo,java.lang.Integer codigoServico,java.lang.String cepDestinatario,br.com.publicaco.correios.ColetaSimultaneaTO coleta,java.lang.String usuario,java.lang.String senha) throws AutenticacaoException , SigepClienteException    { 
        LOG.info("Executing operation validarPostagemSimultanea");
        System.out.println(codAdministrativo);
        System.out.println(codigoServico);
        System.out.println(cepDestinatario);
        System.out.println(coleta);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.lang.Boolean _return = Boolean.valueOf(true);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AutenticacaoException("AutenticacaoException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#buscaServicos(java.lang.String  idContrato ,)java.lang.String  idCartaoPostagem ,)java.lang.String  usuario ,)java.lang.String  senha )*
     */
    public java.util.List<br.com.publicaco.correios.ServicoERP> buscaServicos(java.lang.String idContrato,java.lang.String idCartaoPostagem,java.lang.String usuario,java.lang.String senha) throws AutenticacaoException , SigepClienteException    { 
        LOG.info("Executing operation buscaServicos");
        System.out.println(idContrato);
        System.out.println(idCartaoPostagem);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.util.List<br.com.publicaco.correios.ServicoERP> _return = new java.util.ArrayList<br.com.publicaco.correios.ServicoERP>();
            br.com.publicaco.correios.ServicoERP _returnVal1 = new br.com.publicaco.correios.ServicoERP();
            _returnVal1.setCodigo("Codigo-1407723223");
            _returnVal1.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.580-03:00"));
            _returnVal1.setDatajAtualizacao(Integer.valueOf(-197421122));
            _returnVal1.setDescricao("Descricao2129302747");
            _returnVal1.setHorajAtualizacao(Integer.valueOf(807861883));
            _returnVal1.setId(-3751554378148872457l);
            br.com.publicaco.correios.ServicoSigep _returnVal1ServicoSigep = new br.com.publicaco.correios.ServicoSigep();
            br.com.publicaco.correios.CategoriaServico _returnVal1ServicoSigepCategoriaServico = br.com.publicaco.correios.CategoriaServico.SERVICO_COM_RESTRICAO;
            _returnVal1ServicoSigep.setCategoriaServico(_returnVal1ServicoSigepCategoriaServico);
            br.com.publicaco.correios.ChancelaMaster _returnVal1ServicoSigepChancela = new br.com.publicaco.correios.ChancelaMaster();
            byte[] _returnVal1ServicoSigepChancelaChancela = new byte[] {};
            _returnVal1ServicoSigepChancela.setChancela(_returnVal1ServicoSigepChancelaChancela);
            _returnVal1ServicoSigepChancela.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.581-03:00"));
            _returnVal1ServicoSigepChancela.setDescricao("Descricao1361147666");
            _returnVal1ServicoSigepChancela.setId(-2351078305214817113l);
            java.util.List<br.com.publicaco.correios.ServicoSigep> _returnVal1ServicoSigepChancelaServicosSigep = new java.util.ArrayList<br.com.publicaco.correios.ServicoSigep>();
            _returnVal1ServicoSigepChancela.getServicosSigep().addAll(_returnVal1ServicoSigepChancelaServicosSigep);
            _returnVal1ServicoSigep.setChancela(_returnVal1ServicoSigepChancela);
            _returnVal1ServicoSigep.setExigeDimensoes(Boolean.valueOf(false));
            _returnVal1ServicoSigep.setExigeValorCobrar(Boolean.valueOf(false));
            _returnVal1ServicoSigep.setImitm(2402910443627308058l);
            _returnVal1ServicoSigep.setServico(3453529615644094014l);
            br.com.publicaco.correios.ServicoERP _returnVal1ServicoSigepServicoERP = new br.com.publicaco.correios.ServicoERP();
            _returnVal1ServicoSigepServicoERP.setCodigo("Codigo1123265161");
            _returnVal1ServicoSigepServicoERP.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.582-03:00"));
            _returnVal1ServicoSigepServicoERP.setDatajAtualizacao(Integer.valueOf(-1681831148));
            _returnVal1ServicoSigepServicoERP.setDescricao("Descricao-1108051062");
            _returnVal1ServicoSigepServicoERP.setHorajAtualizacao(Integer.valueOf(-1821695459));
            _returnVal1ServicoSigepServicoERP.setId(-7162629921864085226l);
            br.com.publicaco.correios.ServicoSigep _returnVal1ServicoSigepServicoERPServicoSigep = new br.com.publicaco.correios.ServicoSigep();
            br.com.publicaco.correios.CategoriaServico _returnVal1ServicoSigepServicoERPServicoSigepCategoriaServico = br.com.publicaco.correios.CategoriaServico.SEDEX;
            _returnVal1ServicoSigepServicoERPServicoSigep.setCategoriaServico(_returnVal1ServicoSigepServicoERPServicoSigepCategoriaServico);
            br.com.publicaco.correios.ChancelaMaster _returnVal1ServicoSigepServicoERPServicoSigepChancela = new br.com.publicaco.correios.ChancelaMaster();
            byte[] _returnVal1ServicoSigepServicoERPServicoSigepChancelaChancela = new byte[] {};
            _returnVal1ServicoSigepServicoERPServicoSigepChancela.setChancela(_returnVal1ServicoSigepServicoERPServicoSigepChancelaChancela);
            _returnVal1ServicoSigepServicoERPServicoSigepChancela.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.583-03:00"));
            _returnVal1ServicoSigepServicoERPServicoSigepChancela.setDescricao("Descricao1349824756");
            _returnVal1ServicoSigepServicoERPServicoSigepChancela.setId(2342798231188747999l);
            java.util.List<br.com.publicaco.correios.ServicoSigep> _returnVal1ServicoSigepServicoERPServicoSigepChancelaServicosSigep = new java.util.ArrayList<br.com.publicaco.correios.ServicoSigep>();
            _returnVal1ServicoSigepServicoERPServicoSigepChancela.getServicosSigep().addAll(_returnVal1ServicoSigepServicoERPServicoSigepChancelaServicosSigep);
            _returnVal1ServicoSigepServicoERPServicoSigep.setChancela(_returnVal1ServicoSigepServicoERPServicoSigepChancela);
            _returnVal1ServicoSigepServicoERPServicoSigep.setExigeDimensoes(Boolean.valueOf(false));
            _returnVal1ServicoSigepServicoERPServicoSigep.setExigeValorCobrar(Boolean.valueOf(false));
            _returnVal1ServicoSigepServicoERPServicoSigep.setImitm(5025297375182875189l);
            _returnVal1ServicoSigepServicoERPServicoSigep.setServico(3803137858692108612l);
            br.com.publicaco.correios.ServicoERP _returnVal1ServicoSigepServicoERPServicoSigepServicoERP = new br.com.publicaco.correios.ServicoERP();
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERP.setCodigo("Codigo306108542");
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERP.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.584-03:00"));
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERP.setDatajAtualizacao(Integer.valueOf(-1286739484));
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERP.setDescricao("Descricao1740159785");
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERP.setHorajAtualizacao(Integer.valueOf(-1707991976));
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERP.setId(7414620500781671943l);
                        _returnVal1ServicoSigepServicoERPServicoSigepServicoERP.setServicoSigep(null);
            java.util.List<br.com.publicaco.correios.ServicoAdicionalERP> _returnVal1ServicoSigepServicoERPServicoSigepServicoERPServicosAdicionais = new java.util.ArrayList<br.com.publicaco.correios.ServicoAdicionalERP>();
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERP.getServicosAdicionais().addAll(_returnVal1ServicoSigepServicoERPServicoSigepServicoERPServicosAdicionais);
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERP.setTipo1Codigo("Tipo1Codigo62356063");
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERP.setTipo1Descricao("Tipo1Descricao-1259059422");
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERP.setTipo2Codigo("Tipo2Codigo845790200");
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERP.setTipo2Descricao("Tipo2Descricao-658136955");
            br.com.publicaco.correios.VigenciaERP _returnVal1ServicoSigepServicoERPServicoSigepServicoERPVigencia = new br.com.publicaco.correios.VigenciaERP();
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERPVigencia.setDataFinal(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.585-03:00"));
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERPVigencia.setDataInicial(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.585-03:00"));
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERPVigencia.setDatajFim(Integer.valueOf(4456547));
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERPVigencia.setDatajIni(Integer.valueOf(170703250));
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERPVigencia.setId(Long.valueOf(427636773605233118l));
            _returnVal1ServicoSigepServicoERPServicoSigepServicoERP.setVigencia(_returnVal1ServicoSigepServicoERPServicoSigepServicoERPVigencia);
            _returnVal1ServicoSigepServicoERPServicoSigep.setServicoERP(_returnVal1ServicoSigepServicoERPServicoSigepServicoERP);
            _returnVal1ServicoSigepServicoERPServicoSigep.setSsiCoCodigoPostal("SsiCoCodigoPostal-846640933");
            _returnVal1ServicoSigepServicoERP.setServicoSigep(_returnVal1ServicoSigepServicoERPServicoSigep);
            java.util.List<br.com.publicaco.correios.ServicoAdicionalERP> _returnVal1ServicoSigepServicoERPServicosAdicionais = new java.util.ArrayList<br.com.publicaco.correios.ServicoAdicionalERP>();
            _returnVal1ServicoSigepServicoERP.getServicosAdicionais().addAll(_returnVal1ServicoSigepServicoERPServicosAdicionais);
            _returnVal1ServicoSigepServicoERP.setTipo1Codigo("Tipo1Codigo-697218842");
            _returnVal1ServicoSigepServicoERP.setTipo1Descricao("Tipo1Descricao271041863");
            _returnVal1ServicoSigepServicoERP.setTipo2Codigo("Tipo2Codigo790631975");
            _returnVal1ServicoSigepServicoERP.setTipo2Descricao("Tipo2Descricao-786243");
            br.com.publicaco.correios.VigenciaERP _returnVal1ServicoSigepServicoERPVigencia = new br.com.publicaco.correios.VigenciaERP();
            _returnVal1ServicoSigepServicoERPVigencia.setDataFinal(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.586-03:00"));
            _returnVal1ServicoSigepServicoERPVigencia.setDataInicial(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.587-03:00"));
            _returnVal1ServicoSigepServicoERPVigencia.setDatajFim(Integer.valueOf(-1243605427));
            _returnVal1ServicoSigepServicoERPVigencia.setDatajIni(Integer.valueOf(-136619446));
            _returnVal1ServicoSigepServicoERPVigencia.setId(Long.valueOf(5626093603172024393l));
            _returnVal1ServicoSigepServicoERP.setVigencia(_returnVal1ServicoSigepServicoERPVigencia);
            _returnVal1ServicoSigep.setServicoERP(_returnVal1ServicoSigepServicoERP);
            _returnVal1ServicoSigep.setSsiCoCodigoPostal("SsiCoCodigoPostal-1707723828");
            _returnVal1.setServicoSigep(_returnVal1ServicoSigep);
            java.util.List<br.com.publicaco.correios.ServicoAdicionalERP> _returnVal1ServicosAdicionais = new java.util.ArrayList<br.com.publicaco.correios.ServicoAdicionalERP>();
            br.com.publicaco.correios.ServicoAdicionalERP _returnVal1ServicosAdicionaisVal1 = new br.com.publicaco.correios.ServicoAdicionalERP();
            _returnVal1ServicosAdicionaisVal1.setCodigo("Codigo-1243468859");
            _returnVal1ServicosAdicionaisVal1.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.592-03:00"));
            _returnVal1ServicosAdicionaisVal1.setDatajAtualizacao(Integer.valueOf(-1941708365));
            _returnVal1ServicosAdicionaisVal1.setDescricao("Descricao-1909067720");
            _returnVal1ServicosAdicionaisVal1.setHorajAtualizacao(Integer.valueOf(-592366747));
            _returnVal1ServicosAdicionaisVal1.setId(Integer.valueOf(100185119));
            _returnVal1ServicosAdicionaisVal1.setSigla("Sigla1157786559");
            _returnVal1ServicosAdicionais.add(_returnVal1ServicosAdicionaisVal1);
            _returnVal1.getServicosAdicionais().addAll(_returnVal1ServicosAdicionais);
            _returnVal1.setTipo1Codigo("Tipo1Codigo1862012469");
            _returnVal1.setTipo1Descricao("Tipo1Descricao2019034229");
            _returnVal1.setTipo2Codigo("Tipo2Codigo2128469088");
            _returnVal1.setTipo2Descricao("Tipo2Descricao1429660182");
            br.com.publicaco.correios.VigenciaERP _returnVal1Vigencia = new br.com.publicaco.correios.VigenciaERP();
            _returnVal1Vigencia.setDataFinal(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.593-03:00"));
            _returnVal1Vigencia.setDataInicial(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.593-03:00"));
            _returnVal1Vigencia.setDatajFim(Integer.valueOf(-1188281204));
            _returnVal1Vigencia.setDatajIni(Integer.valueOf(2083111773));
            _returnVal1Vigencia.setId(Long.valueOf(-2162082933560758589l));
            _returnVal1.setVigencia(_returnVal1Vigencia);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AutenticacaoException("AutenticacaoException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#solicitarPostagemScol(java.lang.Integer  codAdministrativo ,)java.lang.String  xml ,)java.lang.String  usuario ,)java.lang.String  senha )*
     */
    public java.lang.String solicitarPostagemScol(java.lang.Integer codAdministrativo,java.lang.String xml,java.lang.String usuario,java.lang.String senha) throws AutenticacaoException , SigepClienteException    { 
        LOG.info("Executing operation solicitarPostagemScol");
        System.out.println(codAdministrativo);
        System.out.println(xml);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.lang.String _return = "_return767166753";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AutenticacaoException("AutenticacaoException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#getStatusCartaoPostagem(java.lang.String  numeroCartaoPostagem ,)java.lang.String  usuario ,)java.lang.String  senha )*
     */
    public br.com.publicaco.correios.StatusCartao getStatusCartaoPostagem(java.lang.String numeroCartaoPostagem,java.lang.String usuario,java.lang.String senha) throws AutenticacaoException , SigepClienteException    { 
        LOG.info("Executing operation getStatusCartaoPostagem");
        System.out.println(numeroCartaoPostagem);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            br.com.publicaco.correios.StatusCartao _return = br.com.publicaco.correios.StatusCartao.SUSPENSO;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AutenticacaoException("AutenticacaoException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#solicitaPLP(java.lang.Long  idPlpMaster ,)java.lang.String  numEtiqueta ,)java.lang.String  usuario ,)java.lang.String  senha )*
     */
    public java.lang.String solicitaPLP(java.lang.Long idPlpMaster,java.lang.String numEtiqueta,java.lang.String usuario,java.lang.String senha) throws AutenticacaoException , SigepClienteException    { 
        LOG.info("Executing operation solicitaPLP");
        System.out.println(idPlpMaster);
        System.out.println(numEtiqueta);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.lang.String _return = "_return-757262310";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AutenticacaoException("AutenticacaoException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#solicitaXmlPlp(java.lang.Long  idPlpMaster ,)java.lang.String  usuario ,)java.lang.String  senha )*
     */
    public java.lang.String solicitaXmlPlp(java.lang.Long idPlpMaster,java.lang.String usuario,java.lang.String senha) throws AutenticacaoException , SigepClienteException    { 
        LOG.info("Executing operation solicitaXmlPlp");
        System.out.println(idPlpMaster);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.lang.String _return = "_return-1269450047";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AutenticacaoException("AutenticacaoException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#obterMotivosPI(*
     */
    public java.util.List<br.com.publicaco.correios.MotivoPIMaster> obterMotivosPI() throws SigepClienteException    { 
        LOG.info("Executing operation obterMotivosPI");
        try {
            java.util.List<br.com.publicaco.correios.MotivoPIMaster> _return = new java.util.ArrayList<br.com.publicaco.correios.MotivoPIMaster>();
            br.com.publicaco.correios.MotivoPIMaster _returnVal1 = new br.com.publicaco.correios.MotivoPIMaster();
            _returnVal1.setCodigo(Integer.valueOf(724154274));
            _returnVal1.setDescricao("Descricao1737964252");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#buscaContrato(java.lang.String  numero ,)long  diretoria ,)java.lang.String  usuario ,)java.lang.String  senha )*
     */
    public br.com.publicaco.correios.ContratoERP buscaContrato(java.lang.String numero,long diretoria,java.lang.String usuario,java.lang.String senha) throws AutenticacaoException , SigepClienteException    { 
        LOG.info("Executing operation buscaContrato");
        System.out.println(numero);
        System.out.println(diretoria);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            br.com.publicaco.correios.ContratoERP _return = new br.com.publicaco.correios.ContratoERP();
            java.util.List<br.com.publicaco.correios.CartaoPostagemERP> _returnCartoesPostagem = new java.util.ArrayList<br.com.publicaco.correios.CartaoPostagemERP>();
            br.com.publicaco.correios.CartaoPostagemERP _returnCartoesPostagemVal1 = new br.com.publicaco.correios.CartaoPostagemERP();
            _returnCartoesPostagemVal1.setCodigoAdministrativo("CodigoAdministrativo1402658941");
            java.util.List<br.com.publicaco.correios.ContratoERP> _returnCartoesPostagemVal1Contratos = new java.util.ArrayList<br.com.publicaco.correios.ContratoERP>();
            _returnCartoesPostagemVal1.getContratos().addAll(_returnCartoesPostagemVal1Contratos);
            _returnCartoesPostagemVal1.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.596-03:00"));
            _returnCartoesPostagemVal1.setDataVigenciaFim(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.597-03:00"));
            _returnCartoesPostagemVal1.setDataVigenciaInicio(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.598-03:00"));
            _returnCartoesPostagemVal1.setDatajAtualizacao(Integer.valueOf(-1816951615));
            _returnCartoesPostagemVal1.setDatajVigenciaFim(Integer.valueOf(93608704));
            _returnCartoesPostagemVal1.setDatajVigenciaInicio(Integer.valueOf(1601186179));
            _returnCartoesPostagemVal1.setDescricaoStatusCartao("DescricaoStatusCartao535192199");
            _returnCartoesPostagemVal1.setDescricaoUnidadePostagemGenerica("DescricaoUnidadePostagemGenerica-1957797847");
            _returnCartoesPostagemVal1.setHorajAtualizacao(Integer.valueOf(-761652710));
            _returnCartoesPostagemVal1.setNumero("Numero21721387");
            java.util.List<br.com.publicaco.correios.ServicoERP> _returnCartoesPostagemVal1Servicos = new java.util.ArrayList<br.com.publicaco.correios.ServicoERP>();
            _returnCartoesPostagemVal1.getServicos().addAll(_returnCartoesPostagemVal1Servicos);
            _returnCartoesPostagemVal1.setStatusCartaoPostagem("StatusCartaoPostagem522707410");
            _returnCartoesPostagemVal1.setStatusCodigo("StatusCodigo-1982095264");
            _returnCartoesPostagemVal1.setUnidadeGenerica("UnidadeGenerica1170357179");
            java.util.List<br.com.publicaco.correios.UnidadePostagemERP> _returnCartoesPostagemVal1UnidadesPostagem = new java.util.ArrayList<br.com.publicaco.correios.UnidadePostagemERP>();
            _returnCartoesPostagemVal1.getUnidadesPostagem().addAll(_returnCartoesPostagemVal1UnidadesPostagem);
            _returnCartoesPostagem.add(_returnCartoesPostagemVal1);
            _return.getCartoesPostagem().addAll(_returnCartoesPostagem);
            br.com.publicaco.correios.ClienteERP _returnCliente = new br.com.publicaco.correios.ClienteERP();
            _returnCliente.setCnpj("Cnpj-1875660645");
            java.util.List<br.com.publicaco.correios.ContratoERP> _returnClienteContratos = new java.util.ArrayList<br.com.publicaco.correios.ContratoERP>();
            br.com.publicaco.correios.ContratoERP _returnClienteContratosVal1 = new br.com.publicaco.correios.ContratoERP();
            java.util.List<br.com.publicaco.correios.CartaoPostagemERP> _returnClienteContratosVal1CartoesPostagem = new java.util.ArrayList<br.com.publicaco.correios.CartaoPostagemERP>();
            _returnClienteContratosVal1.getCartoesPostagem().addAll(_returnClienteContratosVal1CartoesPostagem);
            br.com.publicaco.correios.ClienteERP _returnClienteContratosVal1Cliente = new br.com.publicaco.correios.ClienteERP();
            _returnClienteContratosVal1Cliente.setCnpj("Cnpj-1819623342");
            java.util.List<br.com.publicaco.correios.ContratoERP> _returnClienteContratosVal1ClienteContratos = new java.util.ArrayList<br.com.publicaco.correios.ContratoERP>();
            _returnClienteContratosVal1Cliente.getContratos().addAll(_returnClienteContratosVal1ClienteContratos);
            _returnClienteContratosVal1Cliente.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.599-03:00"));
            _returnClienteContratosVal1Cliente.setDatajAtualizacao(Integer.valueOf(271561800));
            _returnClienteContratosVal1Cliente.setDescricaoStatusCliente("DescricaoStatusCliente239269318");
            java.util.List<br.com.publicaco.correios.GerenteConta> _returnClienteContratosVal1ClienteGerenteConta = new java.util.ArrayList<br.com.publicaco.correios.GerenteConta>();
            _returnClienteContratosVal1Cliente.getGerenteConta().addAll(_returnClienteContratosVal1ClienteGerenteConta);
            _returnClienteContratosVal1Cliente.setHorajAtualizacao(Long.valueOf(-999569630151736664l));
            _returnClienteContratosVal1Cliente.setId(-707216826855425104l);
            _returnClienteContratosVal1Cliente.setInscricaoEstadual("InscricaoEstadual-1651547169");
            _returnClienteContratosVal1Cliente.setNome("Nome642074040");
            _returnClienteContratosVal1Cliente.setStatusCodigo("StatusCodigo-585092326");
            _returnClienteContratosVal1.setCliente(_returnClienteContratosVal1Cliente);
            _returnClienteContratosVal1.setCodigoCliente(-9005510209759340651l);
            _returnClienteContratosVal1.setCodigoDiretoria("CodigoDiretoria174487928");
            br.com.publicaco.correios.ContratoERPPK _returnClienteContratosVal1ContratoPK = new br.com.publicaco.correios.ContratoERPPK();
            _returnClienteContratosVal1ContratoPK.setDiretoria(-5286750481442759123l);
            _returnClienteContratosVal1ContratoPK.setNumero("Numero786570338");
            _returnClienteContratosVal1.setContratoPK(_returnClienteContratosVal1ContratoPK);
            _returnClienteContratosVal1.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.600-03:00"));
            _returnClienteContratosVal1.setDataAtualizacaoDDMMYYYY("DataAtualizacaoDDMMYYYY-2066877173");
            _returnClienteContratosVal1.setDataVigenciaFim(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.600-03:00"));
            _returnClienteContratosVal1.setDataVigenciaFimDDMMYYYY("DataVigenciaFimDDMMYYYY-628248798");
            _returnClienteContratosVal1.setDataVigenciaInicio(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.601-03:00"));
            _returnClienteContratosVal1.setDataVigenciaInicioDDMMYYYY("DataVigenciaInicioDDMMYYYY2072993033");
            _returnClienteContratosVal1.setDatajAtualizacao(Integer.valueOf(-813324295));
            _returnClienteContratosVal1.setDatajVigenciaFim(Integer.valueOf(1329248269));
            _returnClienteContratosVal1.setDatajVigenciaInicio(Integer.valueOf(-1884506871));
            _returnClienteContratosVal1.setDescricaoDiretoriaRegional("DescricaoDiretoriaRegional-1794718727");
            _returnClienteContratosVal1.setDescricaoStatus("DescricaoStatus-1610484324");
            br.com.publicaco.correios.UnidadePostagemERP _returnClienteContratosVal1DiretoriaRegional = new br.com.publicaco.correios.UnidadePostagemERP();
            _returnClienteContratosVal1DiretoriaRegional.setDiretoriaRegional("DiretoriaRegional1148841264");
            br.com.publicaco.correios.EnderecoERP _returnClienteContratosVal1DiretoriaRegionalEndereco = new br.com.publicaco.correios.EnderecoERP();
            _returnClienteContratosVal1DiretoriaRegionalEndereco.setBairro("Bairro-739762718");
            _returnClienteContratosVal1DiretoriaRegionalEndereco.setCep("Cep-1785089847");
            _returnClienteContratosVal1DiretoriaRegionalEndereco.setCidade("Cidade-1825281858");
            _returnClienteContratosVal1DiretoriaRegionalEndereco.setComplemento("Complemento-553909753");
            _returnClienteContratosVal1DiretoriaRegionalEndereco.setComplemento2("Complemento277445253");
            _returnClienteContratosVal1DiretoriaRegionalEndereco.setEnd("End1452041676");
            _returnClienteContratosVal1DiretoriaRegionalEndereco.setId(6256825792928606241l);
            _returnClienteContratosVal1DiretoriaRegionalEndereco.setUf("Uf-1220971418");
            java.util.List<br.com.publicaco.correios.UnidadePostagemERP> _returnClienteContratosVal1DiretoriaRegionalEnderecoUnidadesPostagem = new java.util.ArrayList<br.com.publicaco.correios.UnidadePostagemERP>();
            _returnClienteContratosVal1DiretoriaRegionalEndereco.getUnidadesPostagem().addAll(_returnClienteContratosVal1DiretoriaRegionalEnderecoUnidadesPostagem);
            _returnClienteContratosVal1DiretoriaRegional.setEndereco(_returnClienteContratosVal1DiretoriaRegionalEndereco);
            _returnClienteContratosVal1DiretoriaRegional.setId("Id-1951268080");
            _returnClienteContratosVal1DiretoriaRegional.setNome("Nome214185441");
            _returnClienteContratosVal1DiretoriaRegional.setStatus("Status-179645606");
            _returnClienteContratosVal1DiretoriaRegional.setTipo("Tipo1367204706");
            _returnClienteContratosVal1.setDiretoriaRegional(_returnClienteContratosVal1DiretoriaRegional);
            _returnClienteContratosVal1.setHorajAtualizacao(Integer.valueOf(1469177555));
            _returnClienteContratosVal1.setStatusCodigo("StatusCodigo257738506");
            _returnClienteContratos.add(_returnClienteContratosVal1);
            _returnCliente.getContratos().addAll(_returnClienteContratos);
            _returnCliente.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.602-03:00"));
            _returnCliente.setDatajAtualizacao(Integer.valueOf(1934625133));
            _returnCliente.setDescricaoStatusCliente("DescricaoStatusCliente2016187322");
            java.util.List<br.com.publicaco.correios.GerenteConta> _returnClienteGerenteConta = new java.util.ArrayList<br.com.publicaco.correios.GerenteConta>();
            br.com.publicaco.correios.GerenteConta _returnClienteGerenteContaVal1 = new br.com.publicaco.correios.GerenteConta();
            java.util.List<br.com.publicaco.correios.ClienteERP> _returnClienteGerenteContaVal1ClientesVisiveis = new java.util.ArrayList<br.com.publicaco.correios.ClienteERP>();
            _returnClienteGerenteContaVal1.getClientesVisiveis().addAll(_returnClienteGerenteContaVal1ClientesVisiveis);
            _returnClienteGerenteContaVal1.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.603-03:00"));
            _returnClienteGerenteContaVal1.setDataInclusao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.604-03:00"));
            _returnClienteGerenteContaVal1.setDataSenha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.604-03:00"));
            _returnClienteGerenteContaVal1.setLogin("Login497381684");
            _returnClienteGerenteContaVal1.setMatricula("Matricula2038554886");
            _returnClienteGerenteContaVal1.setSenha("Senha694785740");
            br.com.publicaco.correios.StatusGerente _returnClienteGerenteContaVal1Status = br.com.publicaco.correios.StatusGerente.ATIVO;
            _returnClienteGerenteContaVal1.setStatus(_returnClienteGerenteContaVal1Status);
            br.com.publicaco.correios.TipoGerente _returnClienteGerenteContaVal1TipoGerente = br.com.publicaco.correios.TipoGerente.GERENTE_CONTA_MASTER;
            _returnClienteGerenteContaVal1.setTipoGerente(_returnClienteGerenteContaVal1TipoGerente);
            java.util.List<br.com.publicaco.correios.UsuarioInstalacao> _returnClienteGerenteContaVal1UsuariosInstalacao = new java.util.ArrayList<br.com.publicaco.correios.UsuarioInstalacao>();
            _returnClienteGerenteContaVal1.getUsuariosInstalacao().addAll(_returnClienteGerenteContaVal1UsuariosInstalacao);
            _returnClienteGerenteContaVal1.setValidade("Validade574406306");
            _returnClienteGerenteConta.add(_returnClienteGerenteContaVal1);
            _returnCliente.getGerenteConta().addAll(_returnClienteGerenteConta);
            _returnCliente.setHorajAtualizacao(Long.valueOf(-8495481374997396113l));
            _returnCliente.setId(8431495793031430642l);
            _returnCliente.setInscricaoEstadual("InscricaoEstadual-1502335878");
            _returnCliente.setNome("Nome-948609281");
            _returnCliente.setStatusCodigo("StatusCodigo1903763056");
            _return.setCliente(_returnCliente);
            _return.setCodigoCliente(-8650439920990264278l);
            _return.setCodigoDiretoria("CodigoDiretoria-1765062629");
            br.com.publicaco.correios.ContratoERPPK _returnContratoPK = new br.com.publicaco.correios.ContratoERPPK();
            _returnContratoPK.setDiretoria(-1848338479203887345l);
            _returnContratoPK.setNumero("Numero-678313901");
            _return.setContratoPK(_returnContratoPK);
            _return.setDataAtualizacao(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.606-03:00"));
            _return.setDataAtualizacaoDDMMYYYY("DataAtualizacaoDDMMYYYY1137306634");
            _return.setDataVigenciaFim(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.606-03:00"));
            _return.setDataVigenciaFimDDMMYYYY("DataVigenciaFimDDMMYYYY931874340");
            _return.setDataVigenciaInicio(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.607-03:00"));
            _return.setDataVigenciaInicioDDMMYYYY("DataVigenciaInicioDDMMYYYY-1588414915");
            _return.setDatajAtualizacao(Integer.valueOf(939955996));
            _return.setDatajVigenciaFim(Integer.valueOf(-714445867));
            _return.setDatajVigenciaInicio(Integer.valueOf(-1692323266));
            _return.setDescricaoDiretoriaRegional("DescricaoDiretoriaRegional1280079339");
            _return.setDescricaoStatus("DescricaoStatus253423771");
            br.com.publicaco.correios.UnidadePostagemERP _returnDiretoriaRegional = new br.com.publicaco.correios.UnidadePostagemERP();
            _returnDiretoriaRegional.setDiretoriaRegional("DiretoriaRegional72143370");
            br.com.publicaco.correios.EnderecoERP _returnDiretoriaRegionalEndereco = new br.com.publicaco.correios.EnderecoERP();
            _returnDiretoriaRegionalEndereco.setBairro("Bairro376884294");
            _returnDiretoriaRegionalEndereco.setCep("Cep-1678612099");
            _returnDiretoriaRegionalEndereco.setCidade("Cidade608022631");
            _returnDiretoriaRegionalEndereco.setComplemento("Complemento-1572225347");
            _returnDiretoriaRegionalEndereco.setComplemento2("Complemento2-2089627959");
            _returnDiretoriaRegionalEndereco.setEnd("End1729137593");
            _returnDiretoriaRegionalEndereco.setId(-3103467871311474737l);
            _returnDiretoriaRegionalEndereco.setUf("Uf-1088158265");
            java.util.List<br.com.publicaco.correios.UnidadePostagemERP> _returnDiretoriaRegionalEnderecoUnidadesPostagem = new java.util.ArrayList<br.com.publicaco.correios.UnidadePostagemERP>();
            _returnDiretoriaRegionalEndereco.getUnidadesPostagem().addAll(_returnDiretoriaRegionalEnderecoUnidadesPostagem);
            _returnDiretoriaRegional.setEndereco(_returnDiretoriaRegionalEndereco);
            _returnDiretoriaRegional.setId("Id-1616745812");
            _returnDiretoriaRegional.setNome("Nome-1065227013");
            _returnDiretoriaRegional.setStatus("Status-365180558");
            _returnDiretoriaRegional.setTipo("Tipo-369318162");
            _return.setDiretoriaRegional(_returnDiretoriaRegional);
            _return.setHorajAtualizacao(Integer.valueOf(1699114446));
            _return.setStatusCodigo("StatusCodigo359461419");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AutenticacaoException("AutenticacaoException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#consultaSRO(java.util.List<java.lang.String>  listaObjetos ,)java.lang.String  tipoConsulta ,)java.lang.String  tipoResultado ,)java.lang.String  usuarioSro ,)java.lang.String  senhaSro )*
     */
    public java.lang.String consultaSRO(java.util.List<java.lang.String> listaObjetos,java.lang.String tipoConsulta,java.lang.String tipoResultado,java.lang.String usuarioSro,java.lang.String senhaSro) throws SigepClienteException    { 
        LOG.info("Executing operation consultaSRO");
        System.out.println(listaObjetos);
        System.out.println(tipoConsulta);
        System.out.println(tipoResultado);
        System.out.println(usuarioSro);
        System.out.println(senhaSro);
        try {
            java.lang.String _return = "_return-1223638293";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#obterClienteAtualizacao(java.lang.String  cnpjCliente ,)java.lang.String  usuario ,)java.lang.String  senha )*
     */
    public javax.xml.datatype.XMLGregorianCalendar obterClienteAtualizacao(java.lang.String cnpjCliente,java.lang.String usuario,java.lang.String senha) throws AutenticacaoException , SigepClienteException    { 
        LOG.info("Executing operation obterClienteAtualizacao");
        System.out.println(cnpjCliente);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            javax.xml.datatype.XMLGregorianCalendar _return = javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-04-13T13:15:54.609-03:00");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AutenticacaoException("AutenticacaoException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#integrarUsuarioScol(java.lang.Integer  codAdministrativo ,)java.lang.String  usuario ,)java.lang.String  senha )*
     */
    public java.lang.Boolean integrarUsuarioScol(java.lang.Integer codAdministrativo,java.lang.String usuario,java.lang.String senha) throws AutenticacaoException , SigepClienteException    { 
        LOG.info("Executing operation integrarUsuarioScol");
        System.out.println(codAdministrativo);
        System.out.println(usuario);
        System.out.println(senha);
        try {
            java.lang.Boolean _return = Boolean.valueOf(false);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AutenticacaoException("AutenticacaoException...");
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#obterAssuntosPI(*
     */
    public java.util.List<br.com.publicaco.correios.AssuntoPIMaster> obterAssuntosPI() throws SigepClienteException    { 
        LOG.info("Executing operation obterAssuntosPI");
        try {
            java.util.List<br.com.publicaco.correios.AssuntoPIMaster> _return = new java.util.ArrayList<br.com.publicaco.correios.AssuntoPIMaster>();
            br.com.publicaco.correios.AssuntoPIMaster _returnVal1 = new br.com.publicaco.correios.AssuntoPIMaster();
            _returnVal1.setCodigo(Integer.valueOf(-803415452));
            _returnVal1.setDescricao("Descricao341400158");
            _returnVal1.setTipo("Tipo-915809382");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
    }

    /* (non-Javadoc)
     * @see br.com.publicaco.correios.AtendeCliente#consultaCEP(java.lang.String  cep )*
     */
    public br.com.publicaco.correios.EnderecoERP consultaCEP(java.lang.String cep) throws SigepClienteException , SQLException_Exception    { 
        LOG.info("Executing operation consultaCEP");
        System.out.println(cep);
        try {
            br.com.publicaco.correios.EnderecoERP _return = new br.com.publicaco.correios.EnderecoERP();
            _return.setBairro("Bairro668827325");
            _return.setCep("Cep1768438309");
            _return.setCidade("Cidade1608119837");
            _return.setComplemento("Complemento1260403767");
            _return.setComplemento2("Complemento2-1593436053");
            _return.setEnd("End-1803876320");
            _return.setId(5557957794123769950l);
            _return.setUf("Uf1095684471");
            java.util.List<br.com.publicaco.correios.UnidadePostagemERP> _returnUnidadesPostagem = new java.util.ArrayList<br.com.publicaco.correios.UnidadePostagemERP>();
            br.com.publicaco.correios.UnidadePostagemERP _returnUnidadesPostagemVal1 = new br.com.publicaco.correios.UnidadePostagemERP();
            _returnUnidadesPostagemVal1.setDiretoriaRegional("DiretoriaRegional1826146268");
            br.com.publicaco.correios.EnderecoERP _returnUnidadesPostagemVal1Endereco = new br.com.publicaco.correios.EnderecoERP();
            _returnUnidadesPostagemVal1Endereco.setBairro("Bairro-1072334635");
            _returnUnidadesPostagemVal1Endereco.setCep("Cep-1299176372");
            _returnUnidadesPostagemVal1Endereco.setCidade("Cidade860703923");
            _returnUnidadesPostagemVal1Endereco.setComplemento("Complemento-2077300032");
            _returnUnidadesPostagemVal1Endereco.setComplemento2("Complemento2-594782322");
            _returnUnidadesPostagemVal1Endereco.setEnd("End469922538");
            _returnUnidadesPostagemVal1Endereco.setId(-6392573717395003467l);
            _returnUnidadesPostagemVal1Endereco.setUf("Uf-2064742982");
            java.util.List<br.com.publicaco.correios.UnidadePostagemERP> _returnUnidadesPostagemVal1EnderecoUnidadesPostagem = new java.util.ArrayList<br.com.publicaco.correios.UnidadePostagemERP>();
            _returnUnidadesPostagemVal1Endereco.getUnidadesPostagem().addAll(_returnUnidadesPostagemVal1EnderecoUnidadesPostagem);
            _returnUnidadesPostagemVal1.setEndereco(_returnUnidadesPostagemVal1Endereco);
            _returnUnidadesPostagemVal1.setId("Id978955");
            _returnUnidadesPostagemVal1.setNome("Nome1241370532");
            _returnUnidadesPostagemVal1.setStatus("Status-813487863");
            _returnUnidadesPostagemVal1.setTipo("Tipo-725379126");
            _returnUnidadesPostagem.add(_returnUnidadesPostagemVal1);
            _return.getUnidadesPostagem().addAll(_returnUnidadesPostagem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SigepClienteException("SigepClienteException...");
        //throw new SQLException_Exception("SQLException...");
    }

}
