
package br.com.publicaco.correios;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.16
 * 2017-04-13T13:15:54.539-03:00
 * Generated source version: 2.7.16
 */

@WebFault(name = "Exception", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/")
public class Exception_Exception extends java.lang.Exception {
    
    private br.com.publicaco.correios.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, br.com.publicaco.correios.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, br.com.publicaco.correios.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public br.com.publicaco.correios.Exception getFaultInfo() {
        return this.exception;
    }
}
