
package br.com.publicaco.correios;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.16
 * 2017-04-13T13:15:54.548-03:00
 * Generated source version: 2.7.16
 */

@WebFault(name = "SQLException", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/")
public class SQLException_Exception extends java.lang.Exception {
    
    private br.com.publicaco.correios.SQLException sqlException;

    public SQLException_Exception() {
        super();
    }
    
    public SQLException_Exception(String message) {
        super(message);
    }
    
    public SQLException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public SQLException_Exception(String message, br.com.publicaco.correios.SQLException sqlException) {
        super(message);
        this.sqlException = sqlException;
    }

    public SQLException_Exception(String message, br.com.publicaco.correios.SQLException sqlException, Throwable cause) {
        super(message, cause);
        this.sqlException = sqlException;
    }

    public br.com.publicaco.correios.SQLException getFaultInfo() {
        return this.sqlException;
    }
}
